### ISSUE TITLE
ng-zorro-antd-mobile期待  为Angular生态做出大贡献

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd-mobile#1]
一直是Angular和Ant Design的使用者和喜爱者  十分期待 两个生态的繁荣

**Comment by guoyuanqiang** [comment]
不是ionic。但支持在ionic中使用

**Comment by microwin168** [comment]
ionic4现在出来了，能在ionic4只能够使用吗。
ionic4据说现在都是webComponent了

**Comment by Guoyuanqiang** [comment]
@microwin168 能在ionic4里使用，https://github.com/NG-ZORRO/ng-zorro-antd-mobile/issues/4

**Comment by fisherspy** [comment]
欢迎大家一起参与。

**Comment by menglol** [comment]
@Guoyuanqiang ionic4以下的项目不能使用是吧

**Comment by Guoyuanqiang** [comment]
> @Guoyuanqiang ionic4以下的项目不能使用是吧

@menglol 目前是这样的。
