### ISSUE TITLE
cascader missing from mobile version

### ISSUE THREAD

**Issue by ziegi** [NG-ZORRO/ng-zorro-antd-mobile#10]
## What problem does this feature solve?
I expected all components from ng-zorro-antd to be implemented,
but the nz-cascader seems to be missing
Is there a way of implementing this ?
## What does the proposed API look like?
https://ng.ant.design/components/cascader/en

**Comment by Guoyuanqiang** [comment]
@ziegi Do you mean this component ? http://ng.mobile.ant.design/#/components/picker/zh

**Comment by ziegi** [comment]
I see, you are using the picker in mobile app while using the cascader in the desktop version.

**Comment by fisherspy** [comment]
> I see, you are using the picker in mobile app while using the cascader in the desktop version.

ng-zorro-mobile is the angular completion of ant design mobile([mobile.ant.design](mobile.ant.design)), not the mobile completion of ng-zorro-desktop.
