### ISSUE TITLE
SwipeAction在微信的浏览器中无效

### ISSUE THREAD

**Issue by newmann** [NG-ZORRO/ng-zorro-antd-mobile#100]
## Version
0.9.6
## Environment
微信浏览器
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
使用官网上的代码，在微信浏览器中无效
## What is expected?
能出现官网介绍的效果
## What is actually happening?
无效
## Other?
stackblitz.com上无法重现微信的环境，所以用了一个空白项目。请谅解。

**Comment by BronzeCui** [comment]
你好，经测试，荣耀8-企业微信2.6.2（7888）-扫描官网demo，使用正常。
您是否是在小程序开发中使用我们的组件库，我们的组件库目前没有对小程序开发做特殊的兼容适配，请问能否上传一个可复现问题的简易demo?

**Comment by fisherspy** [comment]
@newmann 由于7天未回应，暂时关闭此issue，后续有必要你可以reopen。
