### ISSUE TITLE
safari  The provided animation property "touch-action" is not a supported CSS property for animations，是因为不支持动画？

### ISSUE THREAD

**Issue by liuliangjia** [NG-ZORRO/ng-zorro-antd-mobile#102]
## Version
0.9.6
## Environment
mac safari
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-qks3k3](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-qks3k3)
## Steps to reproduce
在sarial打开重现链接就可以看到tabs是空白
## What is expected?
正确显示tab
## What is actually happening?
正确显示tab
## Other?
ng6,用了web-animations-js兼容库，还是解决不了问题。

**Comment by fisherspy** [comment]
https://caniuse.com/#search=touch-action @liuliangjia  目前桌面版的safari暂不支持touch-action，手机版本的部分支持

**Comment by fisherspy** [comment]
#106

**Comment by fisherspy** [comment]
@liuliangjia 0.9.8发布修复了MacOS上safari里无法显示的问题，请验证。

**Comment by liuliangjia** [comment]
谢谢！可以正确显示了！
