### ISSUE TITLE
data entry分类下的组件能否实现[(ngModel)]双向绑定呢

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd-mobile#11]
## What problem does this feature solve?
data entry这个分类下的组件如果可以使用ngModel的方式去绑定数据，会更加方便用户的操作，也能更大发挥angular响应式表单的特性
## What does the proposed API look like?
data entry分类下的组件能够实现ControlValueAccessor，用户可以使用[(ngModel)]绑定数据

**Comment by fisherspy** [comment]
部分组件适合 ngModel的，我们会进行支持。

**Comment by tirelyl** [comment]
@fisherspy 好的 3q~

**Comment by fisherspy** [comment]
#159
