### ISSUE TITLE
Add support for danish locale

### ISSUE THREAD

**Issue by michaelkrog** [NG-ZORRO/ng-zorro-antd-mobile#114]
## What problem does this feature solve?
The lack of danish language in the components.
## What does the proposed API look like?
I expect the API to be consistent with implementation of other locales.

**Comment by fisherspy** [comment]
Hi, @michaelkrog , currently there is a narrow vocabulary in nine components locale files, so it is easy to add a new language locale. However, none of us know danish, Would you like to create a PR?

**Comment by michaelkrog** [comment]
Gladly @fisherspy.

However, as I understand the codebase, it needs to be added to ant-design-mobile first, right?
I created a PR for Danish in that here: https://github.com/ant-design/ant-design-mobile/pull/2962

Awaiting it to be merged in.

**Comment by fisherspy** [comment]
@michaelkrog you don't need to add it to ant-design-mobile, it's a react implementation. you just need to create a PR in here.

**Comment by fisherspy** [comment]
#115

**Comment by fisherspy** [comment]
@michaelkrog 0.9.9 is out, Danish is now supported, thanks to you!
