### ISSUE TITLE
在九宮格中，如果显示的item数量超过12个，就报错

### ISSUE THREAD

**Issue by newmann** [NG-ZORRO/ng-zorro-antd-mobile#118]
## Version
0.9.7
## Environment
0.9.7
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-zx42mw](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-zx42mw)
## Steps to reproduce
执行stackbliz上的程序，检查console中的报错信息，即可了解
## What is expected?
能展示过个项目
## What is actually happening?
只能展示12个项目，超过的项目不显示，并报错。

**Comment by fisherspy** [comment]
0.9.9已发布。
