### ISSUE TITLE
在 ngOnInit 使用Toast.fail ,Toast.loading 等方法时 会出现ApplicationRef.tick is called recursively 错误

### ISSUE THREAD

**Issue by TombarthiteL** [NG-ZORRO/ng-zorro-antd-mobile#131]
## Version
0.9.9
## Environment
angular 6.4.7
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-brzqvy](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-brzqvy)
## Steps to reproduce
在 ngOnInit 函数中调用 
## What is expected?
页面加载业务条件不满足  弹出轻提示
## What is actually happening?
报错
## Other?
如实现

**Comment by Guoyuanqiang** [comment]
@TombarthiteL https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ygs47g?file=src/app/app.component.ts
Please wrap with setTimeout
