### ISSUE TITLE
在 ios 8.3 中 InputItem 组件 Button 组件 Navbar 组件 均无法正常显示

### ISSUE THREAD

**Issue by TombarthiteL** [NG-ZORRO/ng-zorro-antd-mobile#132]
## Version
0.9.9
## Environment
angular 6.4.7
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-injnaq](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-injnaq)
## Steps to reproduce
页面兼容问题 测试到 iso 这个版本  基本上大部分组件都无法使用 已经添加了基本的腻子脚本 core-es6 classlist 等 均无法解决 官方说明的环境支持是 ios7  所以希望能支持这个版本 现还有很多人在使用 8.3
## What is expected?
正常显示
## What is actually happening?
页面 输入框 InputItem  点击无反应  不弹出键盘 Button 里面的文字无法显示 Navbar 消失  安卓8.0显示正常 如实例中的调用 在ios8.3中 不具有原有功能

**Comment by fisherspy** [comment]
#139 已提交，新版本release后请验证。 @TombarthiteL

**Comment by TombarthiteL** [comment]
No This problem has not been resolved, Already updated to 0.9.10

**Comment by fisherspy** [comment]
@TombarthiteL 请在你们项目的package.json中增加
`  "browserslist": [
    "iOS >= 7",
    "Android >= 4.4"
  ],`
然后看下是否恢复正常。

**Comment by TombarthiteL** [comment]
@fisherspy  增加了 我按照这边的提交记录 在我本地项目中相同位置 添加了限制

**Comment by TombarthiteL** [comment]
@fisherspy   刚才我才发现我项目目录中有 browserslist 这个文件在修改了这个文件之后 测试已经可以正常显示了  只是 Navbar 的标题居中有些不正常 已经解决

**Comment by fisherspy** [comment]
@TombarthiteL Navbar标题居中不正常是兼容性问题吗，请解释一下。

**Comment by TombarthiteL** [comment]
@fisherspy  不是兼容问题  依旧是动态加载的问题 这边标题是使用 文字拼接插值表达式的方式 如
标题-{{dynamicTitle}}  实际呈现的是 前面 "标题-"这三个字居中了 后面动态生成的文字 会向右靠  整体呈现不居中  依旧是ios8.3 手机
