### ISSUE TITLE
在ios中，点击表单弹出键盘的时候出现了一个白屏，请问这是什么原因

### ISSUE THREAD

**Issue by harrylyh** [NG-ZORRO/ng-zorro-antd-mobile#144]
![img_0246](https://user-images.githubusercontent.com/26681969/49585578-b6622d00-f999-11e8-909f-7e1d5c1acf73.PNG)
![img_0244 20181206-205633](https://user-images.githubusercontent.com/26681969/49585582-b6fac380-f999-11e8-845e-83c3367497d5.jpg)
![img_0245](https://user-images.githubusercontent.com/26681969/49585584-b6fac380-f999-11e8-838c-3d90af5550cc.PNG)

**Comment by fisherspy** [comment]
请问使用了什么组件，是否可以提供stacklitz demo复现？

**Comment by harrylyh** [comment]
> 请问使用了什么组件，是否可以提供stacklitz demo复现？
html：
<ion-content>
  <div class="am-list">
    <nzm-whitespace></nzm-whitespace>
    <nzm-whitespace></nzm-whitespace>
    <div class="am-list-header" text-center>管网构筑物普查</div>
    <div text-center=""><ion-icon style="font-size: 120px" name="contact"></ion-icon></div>
    <div class="am-list-body" text-center>
      <InputItem [type]="'text'" [placeholder]="'请输入账号'">账号</InputItem>
      <InputItem [type]="'password'" [placeholder]="'请输入密码'">密码</InputItem>
    </div>
    <div class="loginBtn" Button [type]="'primary'">登录</div>
    <nzm-whitespace></nzm-whitespace>
    <nzm-whitespace></nzm-whitespace>
    <div text-end><p>忘记密码？</p></div>
  </div>
</ion-content>
scss：
.am-list {
  overflow: auto;
  background: url("./../../../src/assets/img/loginbg.png");
  height: 100%;
  .am-list-header {
    color: white;
    font-size: 20px;
    margin-bottom: 20px;
  }
  .am-list-body {
    top: 10px;
    width: 90%;
    left:5%;
  }

  .loginBtn{
    top:20px;
    width:80%;
    left:10%
  }
}

**Comment by harrylyh** [comment]
> 请问使用了什么组件，是否可以提供stacklitz demo复现？  
<div class="am-list">
    <div class="am-list-header" text-center>管网构筑物普查</div>
    <div text-center=""><ion-icon style="font-size: 120px" name="contact"></ion-icon></div>
    <div class="am-list-body" text-center>
      <InputItem [type]="'text'" [placeholder]="'请输入账号'">账号</InputItem>
      <InputItem [type]="'password'" [placeholder]="'请输入密码'">密码</InputItem>
    </div>
    <div class="loginBtn" Button [type]="'primary'">登录</div>
    <div text-end><p>忘记密码？</p></div>
  </div>

**Comment by harrylyh** [comment]
> 请问使用了什么组件，是否可以提供stacklitz demo复现？

![image](https://user-images.githubusercontent.com/26681969/49586328-d1ce3780-f99b-11e8-820c-aabfac3d4e41.png)
![image](https://user-images.githubusercontent.com/26681969/49586386-f6c2aa80-f99b-11e8-9085-ea0d3476f13a.png)

**Comment by fisherspy** [comment]
@harrylyh 请和 @sWhite01111 协调解决你的问题。
