### ISSUE TITLE
ng-zorro-antd-mobile build aot error

### ISSUE THREAD

**Issue by Dylan-TW** [NG-ZORRO/ng-zorro-antd-mobile#150]
![image](https://user-images.githubusercontent.com/42960490/49725555-eb76c400-fca6-11e8-965b-7b12be50f160.png)

**Comment by Dylan-TW** [comment]
I have checked the source code of this project. It does have some problem.

Let's take an example: the "iconSize" error from the screenshot.

In Step class, there's no iconSize declared. So when I build AOT with option fullTemplateTypeCheck: true, the error occurs.

![image](https://user-images.githubusercontent.com/42960490/49725709-545e3c00-fca7-11e8-9a49-8e162eb632d8.png)
![image](https://user-images.githubusercontent.com/42960490/49725752-6e981a00-fca7-11e8-953f-4e9d82115a02.png)

if fullTemplateTypeCheck is turned to false, there won't be any error. Build according to angular document, this option default value gonna be changed to true.

So I suppose this is important and it will be better to get it fixed.

Thanks

**Comment by fisherspy** [comment]
#227 #223 #224 #157

**Comment by Dylan-TW** [comment]
> @Dylan-TW 目前还剩余ActionSheet待通过fullTemplateTypeCheck，其余组件均已通过检测，请等待下一版本的发布。

OK, thanks. I'll wait.

**Comment by fisherspy** [comment]
> > @Dylan-TW 目前还剩余ActionSheet待通过fullTemplateTypeCheck，其余组件均已通过检测，请等待下一版本的发布。
> 
> OK, thanks. I'll wait.

0.11.2 is out, please verify this issue pls.
