### ISSUE TITLE
Ant Design Mobile of Angular开发公众号 打包后文件太大

### ISSUE THREAD

**Issue by guaicaiboshi** [NG-ZORRO/ng-zorro-antd-mobile#177]
问问大家，Ant Design Mobile of Angular开发公众号 打包后文件好大，有何破解，才写了四五个页面，main.4a3478bbab1ee507f529.js文件就1.8M了，使用的ng build --prod --build-optimizer命令。是不是这个框架不适合做公众号开发？

**Comment by fisherspy** [comment]
请描述下是如何使用组件库的

**Comment by jerrytang67** [comment]
正常用就多300多K左右吧,你怎么用的

**Comment by haoyinag** [comment]
@jerrytang67 我也是开始做公众号开发，请问下你是怎么配置或者怎么打包可以打包体积这么小的，求教
