### ISSUE TITLE
calendar component is difficult to select right minute

### ISSUE THREAD

**Issue by Liiiiimo** [NG-ZORRO/ng-zorro-antd-mobile#188]
## Version
0.9.10
## Environment
android 8.0.0
## Reproduction link
[https://ng-zorro-antd-mobile-start-hx49py.stackblitz.io](https://ng-zorro-antd-mobile-start-hx49py.stackblitz.io)
## Steps to reproduce

<ListItem [arrow]="‘horizontal’" (onClick)=“show=true”>

选择 1月1日8时50分

<Calendar [locale]="‘zhCN’" [visible]=“show” [defaultDate]=“now” [pickTime]="‘true’" [type]="‘range’" [infinite]=“true” (onCancel)=“show=false”

(onConfirm)=“show=false” >

now = new Date； show:boolean = true;
## What is expected?
选择日期之后，选择相应的时分。
After selecting the date, select the appropriate time.
## What is actually happening?
上滑下滑选择分钟的时候，发现重复了上一区域的分钟，例如刚好滚动在15-19分，再上滑的时候，区域不是在20分往后的区域，而是不断地重现10-19分区域。
When you slide down or up to select minutes, you can find that the minutes of the previous area are repeated, for example, just rolling between 15-19 minutes, and then sliding up, the area is not in the 20  area, but continuously reproduces 10- 19 points area.

**Comment by 3fuyu** [comment]
@Liiiiimo It's a bug, I will fix it.

**Comment by Liiiiimo** [comment]
same problem with DatePicker, thinks.

**Comment by 3fuyu** [comment]
it will effective in next version
