### ISSUE TITLE
什么时候可以用ng-zorro-antd-mobile啊

### ISSUE THREAD

**Issue by Shandawei** [NG-ZORRO/ng-zorro-antd-mobile#2]
很期待呢,什么时候可以用啊?

**Comment by guoyuanqiang** [comment]
9月底将会公布，谢谢关注。

**Comment by Shandawei** [comment]
谢谢你们的工作😊

**Comment by microwin168** [comment]
期待～～～马上就月底了。哈哈！

**Comment by Shandawei** [comment]
@microwin168 等的心发慌

**Comment by Yataghan10** [comment]
@Shandawei 不慌不慌

**Comment by Yataghan10** [comment]
@microwin168 马上就来了

**Comment by anterwx** [comment]
目前按照引导使用，需要额外安装rxjs-compat 来弥补 rxjs版本引起的问题，不然demo无法启动

**Comment by Guoyuanqiang** [comment]
@anterwx 已经调整过来了。还没发包

**Comment by Shandawei** [comment]
@Guoyuanqiang 希望ng.mobile.ant.design快点能开，国庆好学习学习，不过我看你们这几天加班，辛苦了😃

**Comment by Guoyuanqiang** [comment]
@Shandawei 哈哈，国庆能赶上

**Comment by anterwx** [comment]
@Shandawei 域名备案没好，然后上午用ip还能访问，现在访问不了了，是关服务了么？
http://120.77.211.27/#/docs/getting-started/zh

**Comment by anterwx** [comment]
@Guoyuanqiang 域名备案没好，然后上午用ip还能访问，现在访问不了了，是关服务了么？
http://120.77.211.27/#/docs/getting-started/zh

**Comment by Shandawei** [comment]
@anterwx .design 域名不能备案啊，话说和主站用的一个域名

**Comment by 3fuyu** [comment]
@anterwx 域名已经恢复：http://ng.mobile.ant.design
