### ISSUE TITLE
0.11.0 Calendar 组件选择完日期选时间报错getFullYear() is not a function.,降回0.10.1正常

### ISSUE THREAD

**Issue by jerrytang67** [NG-ZORRO/ng-zorro-antd-mobile#212]
0.11.0 Calendar 组件选择完日期选时间报错getFullYear() is not a function.,降回0.10.1正常

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/216
