### ISSUE TITLE
aot 模式下 Modal.alert 方法调用保报错

### ISSUE THREAD

**Issue by TombarthiteL** [NG-ZORRO/ng-zorro-antd-mobile#237]
## Version
0.11.1
## Environment
所有环节
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-pjhdl9](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-pjhdl9)
## Steps to reproduce
ng build --prod  --vendor-chunk
## What is expected?
正常
## What is actually happening?
在开发环节下可以成功调用 发布之后就不可以
出现  Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal. 这个错误
查看 ng-zorro-antd-mobile 源码 
错误 出现在 components\core\services\popup.service.ts  
return PopupService.overlayRef.attach(new ComponentPortal(component, undefined, childInjector));
这一行

**Comment by Guoyuanqiang** [comment]
我们项目也aot打包，但无你描述的问题。你的这个在线demo能复现你的问题吗？

**Comment by TombarthiteL** [comment]
@Guoyuanqiang  抱歉 在多次尝试后  我依旧在这个dom中重现这个问题
但是我从我自己项目的调用中看出 似乎 aot 模式下 错误 产生在 node_modules/@angular/cdk/esm5/overlay.es5.js 这个文件中 
而在jit中 调用的是 node_modules/ng-zorro-antd-mobile/node_modules/@angular/cdk/esm5/overlay.es5.js

我是个后端程序 刚接触这一块 不是太确定  是否是我的项目中其他 模块使用了 cdk  而产生的这个问题

**Comment by Guoyuanqiang** [comment]
@TombarthiteL 你看看你的cdk版本是什么

**Comment by Guoyuanqiang** [comment]
@TombarthiteL 或者你在群里问问看看有没有其他人也碰到这个问题？

**Comment by TombarthiteL** [comment]
比较灵异的是 在我删除了  项目下的 node_modules 文件夹 package-lock.json 文件后重新还原包....  这个问题就不再出现了  一句代码没动 .....  有点泪奔   可能是我在升级 angular7.2的时候 还原包存在问题  我是用的ng update

**Comment by TombarthiteL** [comment]
@Guoyuanqiang
