### ISSUE TITLE
tab点击的时候会导致页面回滚到顶部

### ISSUE THREAD

**Issue by lightman0215** [NG-ZORRO/ng-zorro-antd-mobile#241]
## Version
0.11.2
## Environment
ionic4 angular 6
## Steps to reproduce
新建3个tab，然后点击每个tab中的内容多放一点至少可以上下滚动，点击第一个tab后再点击第三个tab，再点击第一个tab时第一个tab的内容回到了顶部，而不是在之前滚动的位置。
## What is expected?
点击任意tab之前的点击过的tab页面滚动条保持在原来的位置
## What is actually happening?
多次点击tab后页面的滚动位置会被重置到顶部，官网示例中也存在此问题，React版本没有此问题。
## Other?
可以查看此DEMO：http://47.99.88.191/test/#/activity-list

**Comment by lightman0215** [comment]
这个问题没有人能回复下么？

**Comment by fisherspy** [comment]
@lightman0215 下一版本会修复

**Comment by fisherspy** [comment]
#399
