### ISSUE TITLE
safari浏览器中，DatePicker设置minDate，可以继续选择比minDate小的日期

### ISSUE THREAD

**Issue by gecc1** [NG-ZORRO/ng-zorro-antd-mobile#242]
Version
0.11.2

Environment
safari浏览器

Steps to reproduce
 <ListItem
      DatePicker
      [extra]="name1"
      [arrow]="'horizontal'"
      [mode]="'date'"
      [locale]="locale"
      [value]="valuedate"
      [minDate]="mindate" 
      (onOk)="ondateOk($event)"
    >Date</ ListItem>

locale = en_US;
name1 = '选择';
minDate = new Date('2019/01/11');
valuedate = new Date();

问题

safari浏览器中，DatePicker设置minDate，呈现最小可选日期为11日，可是继续滚动日期，就出现1-10日的日期，并且可以选择比minDate小的日期

**Comment by fisherspy** [comment]
#243

**Comment by gecc1** [comment]
更新到0.11.3,依然可以选择比minDate小的日期 并报错

[Error] ERROR
TypeError: undefined is not an object (evaluating 'this.selectedTarget[checkIdx].currentY = -arr.indexOf(this.resultArr[checkIdx])')

**Comment by gecc1** [comment]
> #243

更新到0.11.3,依然可以选择比minDate小的日期 并报错

[Error] ERROR
TypeError: undefined is not an object (evaluating 'this.selectedTarget[checkIdx].currentY = -arr.indexOf(this.resultArr[checkIdx])')

**Comment by gecc1** [comment]
我已经解决了。
日期字符串在不同浏览器有不同的实现，例如 new Date('2017-1-1') 在 Safari 上是 Invalid Date，而在 Chrome 上是能正常解析的，改成new Date('2017/1/1') 就ok了


DatePickerComponent.prototype.judgeTime = /**
     * @param {?} arr1
     * @param {?} arr2
     * @return {?}
     */
    function (arr1, arr2) {
        /** @type {?} */
        var date1;
        /** @type {?} */
        var date2;
        //date1 = arr1.slice(0, 3).join('-') + ' ' + arr1.slice(3, 5).join(':');
        //date2 = arr2.slice(0, 3).join('-') + ' ' + arr2.slice(3, 5).join(':');
        date1 = arr1.slice(0, 3).join('/') + ' ' + arr1.slice(3, 5).join(':');
        date2 = arr2.slice(0, 3).join('/') + ' ' + arr2.slice(3, 5).join(':');
        return new Date(date1).getTime() >= new Date(date2).getTime();
    };

**Comment by Guoyuanqiang** [comment]
@gecc1 你的问题解决了，bug是否还会存在？

**Comment by gecc001** [comment]
> @ gecc1你的问题解决了，错误是否还会存在？
错误消失了,

> @gecc1 你的问题解决了，bug是否还会存在？

bug不存在了，就是因为judgeTime里面的new Date()的问题

**Comment by gecc001** [comment]
> @gecc1 你的问题解决了，bug是否还会存在？

bug不存在了，就是因为judgeTime里面的new Date()的问题

**Comment by Guoyuanqiang** [comment]
> > @gecc1 你的问题解决了，bug是否还会存在？
> 
> bug不存在了，就是因为judgeTime里面的new Date()的问题

好的。👍
