### ISSUE TITLE
DatePicker的几个问题

### ISSUE THREAD

**Issue by gecc001** [NG-ZORRO/ng-zorro-antd-mobile#252]
Version
0.11.3

问题：
1：[mode]="'time'" 未设置minDate和maxDate的时候，无法选择0点0分
2：[mode]="'date'"  设置minDate = new Date('2019/01/17');maxDate = new Date('2019/02/10');onOk选中日期2019/02/08，再次打开DatePicker的时候，年月是正确的，日是错误，由此会引发一系列错误
3：待定。。。。。。(后续补充)

**Comment by cannocan** [comment]
DatePicker 滑动就会修改值，点击取消页面上的值未恢复。
antd mobile 滑动时，并不会修改值
# ng-zorro-antd-mobile
![image](https://user-images.githubusercontent.com/7322048/51376091-766a9a00-1b42-11e9-96d3-fd8264de4b49.png)
# ant-design-mobile
![image](https://user-images.githubusercontent.com/7322048/51376126-8b472d80-1b42-11e9-9141-9fbaaea03f0f.png)

**Comment by Guoyuanqiang** [comment]
@cannocan 可以学习下ngmodel的使用
