### ISSUE TITLE
required 在Picker、DatePicker中不起作用

### ISSUE THREAD

**Issue by cannocan** [NG-ZORRO/ng-zorro-antd-mobile#255]
## Version
0.11.2
## Environment
win10,chrome 70,ng-zorro-antd-mobile 0.11.2
## Reproduction link
[https://stackblitz.com/edit/angular-awshyw](https://stackblitz.com/edit/angular-awshyw)
## Steps to reproduce
详见 https://stackblitz.com/edit/angular-awshyw
## What is expected?
required起作用
## What is actually happening?
1、Picker未选中时，起作用，选一项后，失效
2、DatePicker初始值为new Date()时不起作用，初始值为null时，起作用
![image](https://user-images.githubusercontent.com/7322048/51375244-520dbe00-1b40-11e9-81a8-38240666be19.png)

**Comment by fisherspy** [comment]
@cannocan 你这个demo和截图的演示好像不一样

**Comment by cannocan** [comment]
> @cannocan 你这个demo和截图的演示好像不一样

抱歉，这个demo被用来反馈另一个问题了，我关掉这个。。。
