### ISSUE TITLE
Picker's two-way binding action is different from docs

### ISSUE THREAD

**Issue by shawnking07** [NG-ZORRO/ng-zorro-antd-mobile#264]
## Version
0.11.2
## Environment
Windows 10, Chrome 71
## Reproduction link
[https://stackblitz.com/edit/angular-gos7y7](https://stackblitz.com/edit/angular-gos7y7)
## Steps to reproduce
see [link](https://stackblitz.com/edit/angular-gos7y7)
## What is expected?
input and output same data struct like the chosen value

Input 和 Output 使用相同的数据结构，例如文档所述：[value1, value2, value3]
## What is actually happening?
ngModelChange emit the whole chosen element in array, but the input accepts label data

input 接受 label 值，output 传出整个被选择的数组元素

**Comment by ymind** [comment]
这个问题导致双向绑定行为异常，选定项目后再重新展开Picker后，已选定值不会正常反显。

希望早日解决这个问题！
