### ISSUE TITLE
Picker will be init with default value(city data) is no data assigned

### ISSUE THREAD

**Issue by Dylan-TW** [NG-ZORRO/ng-zorro-antd-mobile#266]
If no data assigned, ant design picker will be initialized with default city data from demo-data.

![image](https://user-images.githubusercontent.com/42960490/51658077-d0a3a900-1fe1-11e9-83db-f9f083c702b6.png)
![image](https://user-images.githubusercontent.com/42960490/51658107-e74a0000-1fe1-11e9-8ecf-deb5a48054ed.png)

Assuming I am using picker for selecting names, before names is returned from server, user will see this picker initialized with  datas of China cities not data of names, which is really confusing.
So I suppose this default value is not necessary. Thanks.

**Comment by Guoyuanqiang** [comment]
Thanks. It is a good issue. Maybe data init with user is the best way. We output the default data then user can use it or not.
