### ISSUE TITLE
Stepper step使用小數0.1, 會有浮點數的問題

### ISSUE THREAD

**Issue by peterlai107** [NG-ZORRO/ng-zorro-antd-mobile#277]
## Version
0.11.4
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-jjlgy9?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-jjlgy9?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
請參考stackblitz
## What is expected?
每個step都是0.1增減
## What is actually happening?
2.9->2.8->2.6999999

**Comment by sWhite01111** [comment]
#280
