### ISSUE TITLE
SwipeAction autoClose属性默认false无效

### ISSUE THREAD

**Issue by guaicaiboshi** [NG-ZORRO/ng-zorro-antd-mobile#278]
## Version
0.9.10
## Environment
ng-zorro-antd-mobile版本0.9.10  angular版本7
## Reproduction link
[https://stackblitz.com/edit/angular-dqmhsw-ecnz1h?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-dqmhsw-ecnz1h?file=src/app/app.component.ts)
## Steps to reproduce
滑动向左，出现按钮，点击其中一个，autoClose属性默认false应该是不关闭按钮才对，但是现在按钮还是隐藏起来了。
## What is expected?
滑动向左，出现按钮，点击其中一个，autoClose属性默认false不关闭按钮。
## What is actually happening?
现在按钮还是隐藏起来了。

**Comment by BronzeCui** [comment]
Fixed: #282
