### ISSUE TITLE
InputItem 文本对齐方式

### ISSUE THREAD

**Issue by Jaden9527** [NG-ZORRO/ng-zorro-antd-mobile#279]
## What problem does this feature solve?
InputItem 其他类型能否增加输入的文本右对齐显示
## What does the proposed API look like?
 <InputItem [clear]="true" [KeyboardAlign] = 'right'  [placeholder]="'请输入'">lalala</InputItem>

**Comment by sWhite01111** [comment]
type='money'为自定义实现的input，不是原生的input，所以额外提供了对齐方式接口，原生的可以通过样式text-align来设置
