### ISSUE TITLE
tabs 高度自适应

### ISSUE THREAD

**Issue by Jaden9527** [NG-ZORRO/ng-zorro-antd-mobile#285]
## Version
0.11.4
## Environment
浏览器
## Reproduction link
[https://stackblitz.com/edit/angular-zmxean?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-zmxean?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
不设置高度内容无法显示
## What is expected?
能将组件的高度设置为自适应
## What is actually happening?
tabs内容多为动态取值，高度不确定，固定高度影响显示效果

**Comment by fisherspy** [comment]
会在后续版本优化，目前确实只能设定高度内容。

**Comment by SharpFu** [comment]
需要在tabs/style/index.less中将overflow:hidden改为overflow:visible 就可以实现高度自适应了 @Jaden9527 @fisherspy
