### ISSUE TITLE
actionsheet 和modal 组合使用

### ISSUE THREAD

**Issue by imAcityman** [NG-ZORRO/ng-zorro-antd-mobile#289]
## Version
0.11.4
## Environment
ng6
## Reproduction link
[https://stackblitz.com/edit/angular-sp1hrh](https://stackblitz.com/edit/angular-sp1hrh)
## Steps to reproduce
点击弹出actionsheet，再点击actionsheet上的按钮
## What is expected?
actionsheet关闭并且正确弹出modal
## What is actually happening?
立即弹出modal后，modal会随着actionsheet的关闭一起关闭

**Comment by yoyogis** [comment]
临时workaround:  用200毫秒的setTimeout包一下
`buttonIndex => {
        setTimeout(()=>{
            Modal.alert('Much Buttons', message, [
            { text: 'Button1', onPress: () => console.log('第0个按钮被点击了') },
            { text: 'Button2', onPress: () => console.log('第1个按钮被点击了') },
            { text: 'Button2', onPress: () => console.log('第2个按钮被点击了') }
          ]);
        },200)
      }`

**Comment by imAcityman** [comment]
@yoyogis 是的，我已经用这种方式暂时解决了。只不过这个解决方式用户体验感不够好，而且一旦手机性能差导致卡顿，可能还是会出现问题

**Comment by yoyogis** [comment]
@imAcityman  临时workaround:  return 一个Promise.reject()
buttonIndex => {
        ActionSheet.close();
            Modal.alert('Much Buttons', message, [
            { text: 'Button1', onPress: () => console.log('第0个按钮被点击了') },
            { text: 'Button2', onPress: () => console.log('第1个按钮被点击了') },
            { text: 'Button2', onPress: () => console.log('第2个按钮被点击了') }
        ]);
        return Promise.reject()
      }

**Comment by imAcityman** [comment]
@yoyogis 这个方法可以的，谢谢

**Comment by imAcityman** [comment]
@yoyogis 我又想了一下，这种阻断式的方法应该会导致这个组件本身接下来的流程无法执行。我草测这种问题会出现应该是他actionsheet和modal使用了同一个父层，希望以后的版本可以解决这个问题

**Comment by Guoyuanqiang** [comment]
@imAcityman 👍

**Comment by yoyogis** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/86be97dbfa09d6bad67de1aebfce34fd1d6b02c0/components/action-sheet/action-sheet.service.ts#L80
从代码里看应该不会有什么其他影响。只是阻止了关闭窗口ActionSheet.closeWithAnimation(transitionName, maskTransitionName);
在ActionSheet.closeWithAnimation里有一个setTimeout 200ms然后关闭弹出层，这是罪魁祸首。
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/86be97dbfa09d6bad67de1aebfce34fd1d6b02c0/components/action-sheet/action-sheet.service.ts#L93

不过代码我不是很熟，不知道会不会有未知的影响，还是让 @Guoyuanqiang 老大看看吧。

**Comment by Guoyuanqiang** [comment]
@yoyogis 已经提了pr了。

**Comment by imAcityman** [comment]
@yoyogis 原来官方的组件也会用这种猥琐的方式 😄

**Comment by Guoyuanqiang** [comment]
@imAcityman 😄
