### ISSUE TITLE
Switch、ImagePicker与Ionic兼容问题

### ISSUE THREAD

**Issue by cannocan** [NG-ZORRO/ng-zorro-antd-mobile#303]
## Version
0.11.5
## Environment
ionic4.01  ng0.11.5
## Reproduction link
因为用到了ionic，所以没有提供重现链接，请谅解
## Steps to reproduce
在ionic4中使用Switch、ImagePicker等控件时，点击后，会出现如下所示的空白
![image](https://user-images.githubusercontent.com/7322048/53387541-51c7d480-39c2-11e9-963b-06626dd87179.png)
替换ionic控件则不出现，点击其他地方后，空白消失，目前发现Switch、ImagePicker存在问题
TextareaItem似乎也会出现错位问题（光标不在TextareaItem内）
## What is expected?
不出现空白
## What is actually happening?
有290px空白

**Comment by Guoyuanqiang** [comment]
@cannocan stackblitz支持ionic，建议你还是上个在线demo

**Comment by cannocan** [comment]
> @cannocan stackblitz支持ionic，建议你还是上个在线demo

应该是ng通过input实现，导致了ionic会预留键盘位，这个偶尔会导致部分全面屏手机在微信端，无法点击imagepicker，不是必现

**Comment by Guoyuanqiang** [comment]
@cannocan 好的。
