### ISSUE TITLE
renderHeader shoule be an input ,why a function?

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#304]
## What problem does this feature solve?
Using a function is not convenient here; it should be a string or a template
## What does the proposed API look like?
renderHeader  is string or template

**Comment by Guoyuanqiang** [comment]
Hello, do you mean the List Component?

**Comment by Anberm** [comment]
@Guoyuanqiang Yeah,List Component. I'm sorry. I didn't make it clear

**Comment by Guoyuanqiang** [comment]
@Anberm OK.

**Comment by 3fuyu** [comment]
@Anberm Hi, as you see, our description is 'A configurable Mobile UI components based on Ant Design Mobile'. We base on ant design, so it is. Just like [AntDesignMobile](https://mobile.ant.design/components/list/#List). It depends on our business accumulate.

**Comment by Anberm** [comment]
@3fuyu I think this is the technical point of the implementation difference between react ()=>() can be embedded template, but not ng.
you can see https://codepen.io/anberm/pen/XGJoBJ?&editable=true&editors=001,
![image](https://user-images.githubusercontent.com/34148806/53460362-d1fc4180-3a77-11e9-9ace-e7ade498c092.png)
https://stackblitz.com/edit/angular-wjyj3b?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/34148806/53460434-15ef4680-3a78-11e9-8442-a9081e20a9f8.png)

**Comment by 3fuyu** [comment]
@Anberm 
I understand. Can it solve your problem if renderHeader & renderFooter support string&template&function? We have to used function in some condition, it’s necessary.

**Comment by Anberm** [comment]
Yes, it can

**Comment by 3fuyu** [comment]
@Anberm I will fix it :)

**Comment by 3fuyu** [comment]
@Anberm we will release today.
