### ISSUE TITLE
Using tabbar in the router scenario results in a change in view height

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#316]
## Version
0.11.5
## Environment
win10&Google Chrome 72.0.3626.109
## Reproduction link
[https://stackblitz.com/edit/angular-uqqcvm?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-uqqcvm?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
1.Create multiple routing exits for different tabbars. In this example, I used one route and changed the style .am-tabs-pane-wrap:first-child, .am-tag  position: absolute;
2.click on the page
3.You can see that the fixedbottom location has changed
![tabbar](https://user-images.githubusercontent.com/34148806/53706070-73620980-3e63-11e9-8b62-ae9a6044c623.gif)

## What is expected?
Page height remains the same
## What is actually happening?
Page height change

**Comment by Anberm** [comment]
Perhaps the default value for the paneMoveStyle in the tabs component would be translate3d(0, 0, 0 )

**Comment by fisherspy** [comment]
#399 panMoveStyle has been set to translate3d(0, 0, 0 ), would it be helpful?

**Comment by fisherspy** [comment]
@Anberm

**Comment by Anberm** [comment]
@fisherspy Useful, it has been modified like this in my project. At present, the locally packaged antd-mobile is used in the project, and I will regularly synchronize the official modifications

**Comment by fisherspy** [comment]
OK, we will release a new version today or tomorrow.

**Comment by fisherspy** [comment]
Would you close this issue?

**Comment by Anberm** [comment]
@fisherspy thanks
