### ISSUE TITLE
ng-zorro-antd-mobile.module ,all available components should be exported

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#321]
## What problem does this feature solve?
Now many components are not exported and cannot be referred to in ViewChild. The export of mobile should refer to ng-zorro-antd and export all available components and services
## What does the proposed API look like?
export * from './public-api';

**Comment by fisherspy** [comment]
We will support it in next version

**Comment by fisherspy** [comment]
@Anberm #389
