### ISSUE TITLE
PullToRefresh :The drop-down refresh content area should be the component height

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#326]
## What problem does this feature solve?
The drop-down refresh content area is correspondingly friendlier
## What does the proposed API look like?
.am-pull-to-refresh-content-wrapper{
min-height:PullToRefresh.height;
}
https://stackblitz.com/edit/angular-br4jn6?file=src/app/app.component.ts

![refresh-content](https://user-images.githubusercontent.com/34148806/53926186-807a3500-40bd-11e9-9040-976c0b020ddb.gif)

**Comment by Guoyuanqiang** [comment]
@Anberm Thank you for your report. We'll optimize for the next version.

**Comment by Anberm** [comment]
@Guoyuanqiang nz-mobile lib 任重道远，加油

**Comment by Anberm** [comment]
You can't set height:100% here, it should be min-height:PullToRefresh.height

**Comment by Guoyuanqiang** [comment]
@Anberm 路漫漫👍

**Comment by doneHappyPlay** [comment]
你好，请问你在使用pullToRefresh时，是否存在苹果手机无法下拉加载更多的情况？如果有，你是如何解决的呢？

**Comment by Anberm** [comment]
> 你好，请问你在使用pullToRefresh时，是否存在苹果手机无法下拉加载更多的情况？如果有，你是如何解决的呢？

你可以在我的fork分支上找到相应的修改，但是基于ios特有的滑动卡顿问题，需要从全局上解决，我这边基于better-scroll 封装相应的组件解决

**Comment by DeMeng33** [comment]
you can set 
```
.am-pull-to-refresh-content-wrapper {
  overflow: visible;
}
```
at global

全局设置overflow就好了。。

**Comment by StarkL** [comment]
@Guoyuanqiang 你好， 题主提到的这个问题现在版本好像还存在，而且更糟的是，在小米8机型（全面屏）上，出现列表如何都展示不全的情况 

![微信图片_20190620155002](https://user-images.githubusercontent.com/21234407/59831843-2acc4e80-9375-11e9-8416-a26010bd68a8.jpg)

**Comment by fisherspy** [comment]
@StarkL 是否可以提供stackblitz demo？

**Comment by StarkL** [comment]
@fisherspy 好的，直接从官网http://ng.mobile.ant.design/#/components/pull-to-refresh/zh里的例子即可看到此问题。我这里用微信开发者工具（version：1.02.1904090），调整为iPhoneX机型，即可复现。
![image](https://user-images.githubusercontent.com/21234407/60405320-ef861700-9be1-11e9-833b-e3cc6def67f2.png)

**Comment by BronzeCui** [comment]
> @fisherspy 好的，直接从官网[http://ng.mobile.ant.design/#/components/pull-to-refresh/zh里的例子即可看到此问题。我这里用微信开发者工具（version：1.02.1904090），调整为iPhoneX机型，即可复现。](http://ng.mobile.ant.design/#/components/pull-to-refresh/zh%E9%87%8C%E7%9A%84%E4%BE%8B%E5%AD%90%E5%8D%B3%E5%8F%AF%E7%9C%8B%E5%88%B0%E6%AD%A4%E9%97%AE%E9%A2%98%E3%80%82%E6%88%91%E8%BF%99%E9%87%8C%E7%94%A8%E5%BE%AE%E4%BF%A1%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%EF%BC%88version%EF%BC%9A1.02.1904090%EF%BC%89%EF%BC%8C%E8%B0%83%E6%95%B4%E4%B8%BAiPhoneX%E6%9C%BA%E5%9E%8B%EF%BC%8C%E5%8D%B3%E5%8F%AF%E5%A4%8D%E7%8E%B0%E3%80%82)
> ![image](https://user-images.githubusercontent.com/21234407/60405320-ef861700-9be1-11e9-833b-e3cc6def67f2.png)
> 
> 谢谢！

组件目前需要自行设置高度，官方例子高度设置为700px，若要撑满全屏，可设置高度为window.innerHeight
