### ISSUE TITLE
input-item value shoule be tostring & defaultValue should not override the value

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#327]
## Version
0.11.6
## Environment
win10&Google Chrome 72.0.3626.109
## Reproduction link
[https://stackblitz.com/edit/angular-dmcigx?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-dmcigx?file=src/app/app.component.ts)
## Steps to reproduce
1.value = 789,defaultvalue not input
2.Click the delete or number
3.defaultValue should not override the value
## What is expected?
1.2:The value is normally deleted or changed
3: input-item show value 789
## What is actually happening?
1.2:Delete times error, change when the implementation of the plus operation
3:input-item show value '' ,Because the input value is overwritten by the default value
## Other?
![inputitem](https://user-images.githubusercontent.com/34148806/53928548-8542e700-40c5-11e9-899e-a49eac13ecd3.gif)

**Comment by Anberm** [comment]
![image](https://user-images.githubusercontent.com/34148806/53928855-993b1880-40c6-11e9-96a8-d39c1d734818.png)

**Comment by Anberm** [comment]
The default might be this:
![image](https://user-images.githubusercontent.com/34148806/53928875-b66fe700-40c6-11e9-86f6-4829b80c49c4.png)

**Comment by sWhite01111** [comment]
#330

**Comment by fisherspy** [comment]
@Anberm has #330  solved your issue?

**Comment by Anberm** [comment]
@fisherspy @sWhite01111 All right, thank you
