### ISSUE TITLE
Pickup组件BUG

### ISSUE THREAD

**Issue by jerrytang67** [NG-ZORRO/ng-zorro-antd-mobile#332]
发布prod版本后才会有这个BUG

官方发布版就有问题
最上面的用方法触发的 选择 pickup第一次触发以后 
overlay-container中没有 dispaly:none,导致全页不能点击
整页一直在cancel
http://ng.mobile.ant.design/#/components/picker/picker-demo-zh?lang=zh-CN

**Comment by cannocan** [comment]
actionsheet、modal也存在问题，希望尽快修复
另外grid不支持iconfont了，之前的版本支持
