### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by luokeyuan** [NG-ZORRO/ng-zorro-antd-mobile#334]
ERROR in node_modules\ng-zorro-antd-mobile\ng-zorro-antd-mobile.d.ts.ɵu.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules\ng-zorro-antd-mobile\ng-zorro-antd-mobile.d.ts.ɵu.html(18,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.

**Comment by Guoyuanqiang** [comment]
@luokeyuan Hi, please write more details just like build your app or build lib.
