### ISSUE TITLE
Picker Component returns an incorrect value and selects an error message

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#336]
## Version
0.11.6
## Environment
win10&Google Chrome 72.0.3626.109
## Reproduction link
[https://stackblitz.com/edit/angular-svcrau?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-svcrau?file=src/app/app.component.ts)
## Steps to reproduce
1.Multiple components used together
2.Open

![picker](https://user-images.githubusercontent.com/34148806/54173866-9f623800-44be-11e9-9570-b180794f35ef.gif)
## What is expected?
Normal operation, and the return value is normal
## What is actually happening?
error
## Other?
Maybe the community can work together to fix it

**Comment by Guoyuanqiang** [comment]
@Anberm I try to use like demo is OK. I will check why func return Array as data input is error. https://stackblitz.com/edit/angular-svcrau-bssckp?file=src/app/app.component.ts.
