### ISSUE TITLE
Picker

### ISSUE THREAD

**Issue by imAcityman** [NG-ZORRO/ng-zorro-antd-mobile#339]
## Version
0.11.7
## Environment
windows chrome
## Reproduction link
[https://rbnugn.run.stackblitz.io](https://rbnugn.run.stackblitz.io)
## Steps to reproduce
点击最后一个listitem
## What is expected?
展示popup
## What is actually happening?
调起popup后，最后一个listitem明显多出一个border-bottom

**Comment by Guoyuanqiang** [comment]
@imAcityman 在线demo发一下，你这发的是preview页面

**Comment by imAcityman** [comment]
@Guoyuanqiang 这就是picker api的示例，因为api的示例最下面一个是disabled所以正常看不出效果，但是把disabled干掉然后再点击最下面那个piker这个小问题就出现了

**Comment by Guoyuanqiang** [comment]
@imAcityman 
![image](https://user-images.githubusercontent.com/6535259/54265928-5343f000-45b1-11e9-90ac-288748823920.png)

**Comment by imAcityman** [comment]
![1552468345(1)](https://user-images.githubusercontent.com/19684971/54266887-390b1180-45b3-11e9-8af3-9c2bfec83942.jpg)
我找了一下原因发现这个媒介查询并没有适配到我的手机屏幕导致的

**Comment by Guoyuanqiang** [comment]
@imAcityman 好的。👍
