### ISSUE TITLE
doc optimize

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#341]
## What problem does this feature solve?
The documentation needs to accurately describe the input/output, the type, and whether the binding is bi-directional,
For example, the value attribute of input-item, which is only input, has little significance because ngModel can achieve the same effect and value cannot be Two-way binding
## What does the proposed API look like?
Reference ng-zorro doc https://ng.ant.design/components/input/zh

**Comment by fisherspy** [comment]
@Anberm we share the most part of API docs with ant design mobile of React, If you have questions, pls give us more detailed information, thank you.
