### ISSUE TITLE
TabBar 索引activeTab绑定问题

### ISSUE THREAD

**Issue by qtbui159** [NG-ZORRO/ng-zorro-antd-mobile#343]
## Version
0.11.7
## Environment
firefox,chrome,手机浏览器 均有此问题
## Reproduction link
[https://stackblitz.com/edit/angular-zee7jl](https://stackblitz.com/edit/angular-zee7jl)
## Steps to reproduce
点击 Click to next tab-bar 
## What is expected?
4个tabpane依次切换，并且应该有选中效果
## What is actually happening?
tabpane没有依次切换，而是跳着的，并且被选中的tabpane 没有选中效果

**Comment by fisherspy** [comment]
#345

**Comment by qtbui159** [comment]
> #345

thx
