### ISSUE TITLE
ActionSheet动作面板问题

### ISSUE THREAD

**Issue by HDONGDeveloper** [NG-ZORRO/ng-zorro-antd-mobile#347]
ActionSheet动作面板 
在引入使用后 提示   Cannot read property posittion of null 
麻烦查一下

**Comment by Guoyuanqiang** [comment]
@HDONGDeveloper 请细看下demo，这是没有初始化ActionSheet

**Comment by HDONGDeveloper** [comment]
> @HDONGDeveloper 请细看下demo，这是没有初始化ActionSheet
在 对应的module中 加入了 entryComponents:ActionSheet

**Comment by Guoyuanqiang** [comment]
@HDONGDeveloper 
![image](https://user-images.githubusercontent.com/6535259/54576250-549e6e00-4a32-11e9-964b-9218ca517f39.png)

**Comment by HDONGDeveloper** [comment]
> @HDONGDeveloper
> ![image](https://user-images.githubusercontent.com/6535259/54576250-549e6e00-4a32-11e9-964b-9218ca517f39.png)

StaticInjectorError(AppModule)[DashboardComponent -> ActionSheet]: 
  StaticInjectorError(Platform: core)[DashboardComponent -> ActionSheet]:

**Comment by Guoyuanqiang** [comment]
@HDONGDeveloper https://stackblitz.com/edit/angular-wlszkl?file=src/app/app.module.ts

**Comment by HDONGDeveloper** [comment]
> @HDONGDeveloper https://stackblitz.com/edit/angular-wlszkl?file=src/app/app.module.ts

非常感谢 我在此demo上 调试出来了 我去找一下我的问题 谢谢

**Comment by HDONGDeveloper** [comment]
还有一个问题 就是 缺少PopUp 组件

**Comment by Guoyuanqiang** [comment]
@HDONGDeveloper 有报错吗？

**Comment by HDONGDeveloper** [comment]
没有 ActionSheet动作面板 已经好了 非常感谢

**Comment by Guoyuanqiang** [comment]
@HDONGDeveloper 好的。欢迎pr
