### ISSUE TITLE
Grid组件无法动态加载元素

### ISSUE THREAD

**Issue by duqian42707** [NG-ZORRO/ng-zorro-antd-mobile#351]
## Version
0.11.6
## Environment
Mac OS X Chrome 72.0.3626.121
## Reproduction link
[https://stackblitz.com/edit/angular-yvxjew?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-yvxjew?file=src/app/app.component.ts)
## Steps to reproduce
点击Grid中的某个元素
## What is expected?
删除该元素
## What is actually happening?
页面上没有删除该元素

**Comment by Guoyuanqiang** [comment]
@duqian42707 https://stackblitz.com/edit/angular-yvxjew-sqmedz?file=src/app/app.component.ts
