### ISSUE TITLE
Accordion手风琴加载远程数据时无法自动展开面板

### ISSUE THREAD

**Issue by duqian42707** [NG-ZORRO/ng-zorro-antd-mobile#354]
## Version
0.11.7
## Environment
Mac OS X Chome
## Reproduction link
[https://stackblitz.com/edit/angular-etquh1](https://stackblitz.com/edit/angular-etquh1)
## Steps to reproduce
直接运行即可
## What is expected?
三个面板应都是展开的状态
## What is actually happening?
三个面板都是折叠的状态

**Comment by nanasennman** [comment]
前两天也碰到了这个问题来着，目前自己的非根本性的解决方案是：

1.Accordion里加个属性expandAll="true"
2.再加一个不显示出来的AccordionPanel
```
<AccordionPanel style="display:none"></AccordionPanel>
```
仅供参考……
