### ISSUE TITLE
InputItem组件的extra属性引用ngTemplate的时候显示为[object Object]

### ISSUE THREAD

**Issue by ymind** [NG-ZORRO/ng-zorro-antd-mobile#358]
## Version
0.11.7
## Environment
ng-zorro-antd-mobile
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-xr1beb](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-xr1beb)
## Steps to reproduce
见重现链接
## What is expected?
展示ng-template的内容
## What is actually happening?
展示为[object Object]

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/353

**Comment by nuonuoge** [comment]
@dusdong  https://github.com/NG-ZORRO/ng-zorro-antd-mobile/releases/tag/0.11.8
