### ISSUE TITLE
[Tabs组件]当每个tab字数不相同时，能否实现相邻tab的字跟字的间距相同

### ISSUE THREAD

**Issue by zpaul** [NG-ZORRO/ng-zorro-antd-mobile#359]
## What problem does this feature solve?
目前是通过【page】属性来决定每一页显示几个tab，然后根据page值来算出每个tab所占宽度的百分比。这会有一个问题，比如第一个tab是三个字，第二个tab是四个字，第三个tab是两个字，那么他们之间的间距就会不同，从而使得显示效果不太美观
## What does the proposed API look like?
通过提供一个额外的属性让用户选择是等百分比布局还是等间距布局

**Comment by qqis314860100** [comment]
+1，当把page设置为“”时，可以不用%做间距，但是会失去点击tab偏移位置的功能。

**Comment by fisherspy** [comment]
#399 新增tabTitleSize自定义title的尺寸（单位：px），但是约定每个title的尺寸相同。这主要是考虑到美观问题。

**Comment by fisherspy** [comment]
@qqis314860100 现在不需要自己猜百分比，直接设置尺寸即可，这样是否比以前更方便？

**Comment by fisherspy** [comment]
@zpaul
