### ISSUE TITLE
InputItem使用动态标题，样式问题

### ISSUE THREAD

**Issue by cannocan** [NG-ZORRO/ng-zorro-antd-mobile#361]
## Version
0.11.7
## Environment
ionic4 ng-zorro-antd_mobile：0.11.7
## Reproduction link
[https://stackblitz.com/edit/angular-awshyw](https://stackblitz.com/edit/angular-awshyw)
## Steps to reproduce
标题动态获取
![image](https://user-images.githubusercontent.com/7322048/54969586-a78b9e80-4fb9-11e9-9046-fd537a604c51.png)

## What is expected?
样式不变
## What is actually happening?
字体变小

**Comment by sWhite01111** [comment]
#364

**Comment by cannocan** [comment]
![image](https://user-images.githubusercontent.com/7322048/55847285-3e8c5500-5b7b-11e9-84e4-e51c887ec2d0.png)
![image](https://user-images.githubusercontent.com/7322048/55847292-46e49000-5b7b-11e9-9a38-6fda6efe85d7.png)
更新后，视觉上有个变化过程，体验不是很好，有时还能看到input原始框框，一闪而过，拍视频截图的，不是很清晰，望见谅

**Comment by sWhite01111** [comment]
#377 不好意思，上次没有注意这个问题
