### ISSUE TITLE
标签页tabs的tabbar只有两个标签时仍然可以滚动

### ISSUE THREAD

**Issue by imAcityman** [NG-ZORRO/ng-zorro-antd-mobile#365]
## Version
0.11.7
## Environment
0.11.X
## Reproduction link
[https://stackblitz.com/edit/angular-vgfept](https://stackblitz.com/edit/angular-vgfept)
## Steps to reproduce
tab标签只有2个时，按住tabbar滑动
## What is expected?
tab页<=3时除了tab切换动画，不应该出现任何多余的效果，或者可以手动配置效果
## What is actually happening?
按住tabbar可以来回滑动1px，并且左右会出现白色背景，但是当标签只有3个时就不会出现这种情况

**Comment by fisherspy** [comment]
#399
