### ISSUE TITLE
ios使用ImagePicker拍摄或上传的照片角度不对

### ISSUE THREAD

**Issue by sandyisone** [NG-ZORRO/ng-zorro-antd-mobile#367]
## Version
0.11.7
## Environment
ios
## Reproduction link
[https://mxtqus.run.stackblitz.io](https://mxtqus.run.stackblitz.io)
## Steps to reproduce
选择一个照片上传
## What is expected?
照片角度正确
## What is actually happening?
照片旋转270度

**Comment by Anberm** [comment]
you can try :
 rotateImg(image, orientation, canvas) {
    const height = image.height;
    const width = image.width;
    const ctx = canvas.getContext('2d');
    switch (orientation) {
      case 1:
        console.log('rotate 0°');
        break;
      case 6:
        console.log('rotate 90°');
        canvas.height = width;
        canvas.width = height;
        ctx.rotate(Math.PI / 2);
        ctx.translate(0, -height);
        ctx.drawImage(image, 0, 0);
        break;
      case 3:
        console.log('rotate 180°');
        canvas.height = height;
        canvas.width = width;
        ctx.rotate(Math.PI);
        ctx.translate(-width, -height);
        ctx.drawImage(image, 0, 0);
        break;
      case 8:
        console.log('rotate 270°');
        canvas.height = width;
        canvas.width = height;
        ctx.rotate(-Math.PI / 2);
        ctx.translate(-height, 0);
        ctx.drawImage(image, 0, 0);
        break;
      case 0:
        console.log('rotate 90°');
        canvas.height = width;
        canvas.width = height;
        ctx.rotate(Math.PI / 2);
        ctx.translate(0, -height);
        ctx.drawImage(image, 0, 0);
        break;
      case undefined:
        console.log('undefined  not rotate');
        break;
    }
  }
