### ISSUE TITLE
DatePick组件的mode为month的时候，微信ios平台报错

### ISSUE THREAD

**Issue by WangHone** [NG-ZORRO/ng-zorro-antd-mobile#369]
## Version
0.11.7
## Environment
ios12.2
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-guh5ul?file=package.json](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-guh5ul?file=package.json)
## Steps to reproduce
DatePick组件的mode为month的时候，微信ios平台报错
## What is expected?
选择年和月
## What is actually happening?
系统报错
## Other?
这个问题再0.11.7解决了,但是昨天更新了ios12.2后问题又出现了

**Comment by Guoyuanqiang** [comment]
@Guoyuanqiang 麻烦贴一下报错信息

**Comment by WangHone** [comment]
取到的日期是NaN

**Comment by fisherspy** [comment]
@WangHone 1.0.0-beta.0是否恢复正常？

**Comment by fisherspy** [comment]
使用ios版微信扫码:https://ng-zorro-antd-mobile-start-guh5ul.stackblitz.io ，选择月份确定后全部是NaN。

**Comment by Guoyuanqiang** [comment]
@WangHone https://stackblitz.com/edit/ng-zorro-antd-mobile-start-aaakjd?file=src/app/app.component.ts

**Comment by fisherspy** [comment]
@WangHone 升级组件库版本号即可。
