### ISSUE TITLE
与ionic整合后，将zorro-mobile的list放在ion-content中，在android端的微信上列表的间隔线没有显示。

### ISSUE THREAD

**Issue by WangHone** [NG-ZORRO/ng-zorro-antd-mobile#370]
## Version
0.11.7
## Environment
Android端的微信
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
与ionic整合后，将zorro-mobile的list放在ion-content中，在android端的微信上列表的间隔线没有显示。
## What is expected?
列表显示间隔线
## What is actually happening?
列表没有显示间隔线
## Other?
官方提供的stackblitz整合ionic失败，所以没有提供相应的stackblitz。

**Comment by 3fuyu** [comment]
@WangHone 请想办法提供能够复现的demo，否则无法定位问题
