### ISSUE TITLE
how to use postcss's plugin "postcss-px-to-viewport" in angular 在angular-mobile中使用"postcss-px-to-viewport" 这个插件

### ISSUE THREAD

**Issue by haoyinag** [NG-ZORRO/ng-zorro-antd-mobile#374]
## What problem does this feature solve?
use vw/vh to exchange px in mobile
可以在移动端中使用"postcss-px-to-viewport" 这个插件，解决angular在移动端的适配问题
## What does the proposed API look like?
hope that can provide the method of useing this plugin in angular...

**Comment by fisherspy** [comment]
请问你们的适配方案是怎样的？

**Comment by haoyinag** [comment]
@fisherspy 我们？angular项目只能手动写媒体查询...
@vthinkxie @michaelkrog @Shandawei  is there no way ?

**Comment by fisherspy** [comment]
> @fisherspy 我们？angular项目只能手动写媒体查询...
> @vthinkxie @michaelkrog @Shandawei is there no way ?

我们没有使用过"postcss-px-to-viewport" 。

**Comment by haoyinag** [comment]
@fisherspy 请问怎么使用

**Comment by fisherspy** [comment]
> @fisherspy 请问怎么使用

我们直接在代码里使用px或者rem，没有用插件做转换。

**Comment by vthinkxie** [comment]
@haoyinag https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack
