### ISSUE TITLE
icon svg XML namespace does not work with HTTPS

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#380]
## What problem does this feature solve?
I saw a submission 62b0d9 that changed HTTPS, but for the SVG namespace using HTTPS, browser recognition failed.
e.g.:
data:image/svg xml;charset=utf-8,<svg%20width%3D"16"%20height%3D"26"%20viewBox%3D"0%200%2016%2026"%20version%3D"1.1"%20xmlns%3D"https%3A%2F%2Fwww.w3.org%2F2000%2Fsvg"%20xmlns%3Axlink%3D"https%3A%2F%2Fwww.w3.org%2F1999%2Fxlink"><g%20id%3D"UI-KIT_%E5%9F%BA%E7%A1%80%E5%85%83%E4%BB%B6"%20stroke%3D"none"%20stroke-width%3D"1"%20fill%3D"none"%20fill-rule%3D"evenodd"><g%20id%3D"9.9%E5%9F%BA%E7%A1%80%E5%85%83%E4%BB%B6"%20transform%3D"translate(-5809.000000%2C%20-8482.000000)"%20fill%3D"%23C7C7CC"><polygon%20id%3D"Disclosure-Indicator"%20points%3D"5811%208482%205809%208484%205820.5%208495%205809%208506%205811%208508%205825%208495"><%2Fpolygon><%2Fg><%2Fg><%2Fsvg>

![image](https://user-images.githubusercontent.com/34148806/55935376-0d3c8380-5c66-11e9-8aa7-2e2f1d67a0d6.png)

HTTP works fine
![image](https://user-images.githubusercontent.com/34148806/55935417-27766180-5c66-11e9-92de-0b016a7d52fd.png)

## What does the proposed API look like?
Restore to HTTP

**Comment by fisherspy** [comment]
#388 fixed
