### ISSUE TITLE
似乎运行不了

### ISSUE THREAD

**Issue by enddering** [NG-ZORRO/ng-zorro-antd-mobile#39]
## Version
0.9.4
## Environment
stackblitz
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-xkthd7](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-xkthd7)
## Steps to reproduce
https://stackblitz.com/edit/ng-zorro-antd-mobile-start-xkthd7 打开即可
## What is expected?
能运行吧
## What is actually happening?
你猜
## Other?
就看文档测试一下。。。

**Comment by 3fuyu** [comment]
有时候需要科学上网

**Comment by microwin168** [comment]
@enddering 你需要设置    entryComponents: [ToastComponent, ActionSheetComponent], 如下
https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ajghhf

**Comment by enddering** [comment]
> @enddering 你需要设置 entryComponents: [ToastComponent, ActionSheetComponent], 如下
> https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ajghhf

多谢，希望官方每一个demo都有stackblitz就好了😊

**Comment by 3fuyu** [comment]
> > @enddering 你需要设置 entryComponents: [ToastComponent, ActionSheetComponent], 如下
> > https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ajghhf
> 
> 多谢，希望官方每一个demo都有stackblitz就好了😊

每一个demo都有stackblitz，可以在官网文档中查看
![image](https://user-images.githubusercontent.com/9128418/46871284-8566ef80-ce63-11e8-84a3-d8e6ff179083.png)

**Comment by enddering** [comment]
> > > @enddering 你需要设置 entryComponents: [ToastComponent, ActionSheetComponent], 如下
> > > https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ajghhf
> > 
> > 
> > 多谢，希望官方每一个demo都有stackblitz就好了😊
> 
> 每一个demo都有stackblitz，可以在官网文档中查看
> ![image](https://user-images.githubusercontent.com/9128418/46871284-8566ef80-ce63-11e8-84a3-d8e6ff179083.png)

抱歉我没注意到这个，但是似乎还是有问题，https://ng.mobile.ant.design/#/components/toast/zh
[链接过去似乎还是不完整的代码导致无法运行😅]
<img width="1680" alt="screen shot 2018-10-12 at 11 38 19 pm" src="https://user-images.githubusercontent.com/16018453/46879359-6888e700-ce78-11e8-934a-50a810718255.png">

**Comment by 3fuyu** [comment]
@enddering master分支已经修复该bug，可以在本地运行查看，官网下次发版后可以验证

**Comment by enddering** [comment]
> @enddering master分支已经修复该bug，可以在本地运行查看，官网下次发版后可以验证
多谢，辛苦了

**Comment by 3fuyu** [comment]
@enddering 官网已可以预览
