### ISSUE TITLE
执行 ng add ng-zorro-antd-mobile 命令后，报错

### ISSUE THREAD

**Issue by VEMTK** [NG-ZORRO/ng-zorro-antd-mobile#392]
## Version
0.11.9
## Environment
 ng-zorro-antd-mobile
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
$ ng new PROJECT_NAME
$ cd PROJECT_NAME
$ ng add ng-zorro-antd-mobile

## What is expected?
添加成功
## What is actually happening?
ERROR:no schema with key or ref "https://json-schema.org/schema"

知道问题在 ajv\lib\ajv.js:91:19 ,但是不知道要怎么改。

**Comment by fisherspy** [comment]
#393
