### ISSUE TITLE
win10环境npm start启动失败

### ISSUE THREAD

**Issue by nuonuoge** [NG-ZORRO/ng-zorro-antd-mobile#40]
开发环境：win10
全局cli版本：
Your global Angular CLI version (6.2.5) is greater than your local
version (6.2.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Angular CLI: 6.2.4
Node: 10.8.0
OS: win32 x64
Angular: 6.1.9

zorro mobile cli版本:6.2.3

失败信息：
ng-zorro-antd-mobile\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list

个人觉得改成这样更保险，在win10和linux这样是可以启动的（mac没有验证）：npm run site:init && node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve --port 4300 --host 0.0.0.0 --deploy-url=/

**Comment by nuonuoge** [comment]
在mac上试了，可以用，但是还没找到win10上失败的原因

**Comment by nuonuoge** [comment]
全局的版本有时未必和node_modules相同，也许也会有问题，我们项目是需要配置max_old_space_size的，工程略大

**Comment by 3fuyu** [comment]
@nuonuoge 这个只是官网网站项目的 package.json，和你项目的配置无关的，你的项目可以按照实际情况自由配置
