### ISSUE TITLE
Toast轻提示位置可调整需求

### ISSUE THREAD

**Issue by GeniusLuo** [NG-ZORRO/ng-zorro-antd-mobile#400]
## What problem does this feature solve?
Toast轻提示在提示消息时，位置永远是屏幕中心处，这样对于加载或者错误提示很友好，但是对于纯文字信息展示时不够美观，希望可以添加一个参数让用户来控制Toast在屏幕中的位置。
## What does the proposed API look like?
Toast.info(content, duration, onClose, mask) 改为 Toast.info(content, duration, onClose, mask, style)

**Comment by GeniusLuo** [comment]
![image](https://user-images.githubusercontent.com/25976359/56884462-76146000-6a9c-11e9-801f-06c833f54a1b.png)
如果，位置可以自定义调整就好了。
第一次提issues，有点小激动，如果有任何不正确的请指出，谢谢。

**Comment by Guoyuanqiang** [comment]
@GeniusLuo 棒

**Comment by fisherspy** [comment]
@GeniusLuo #450 满足要求吗？

**Comment by nuonuoge** [comment]
@GeniusLuo 目前只提供了上中下三个位置，如果不满足，可以暂时在自己项目中通过css覆盖实现位置控制

**Comment by GeniusLuo** [comment]
非常感谢！
