### ISSUE TITLE
toast.service build prod error

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#412]
## Version
0.12.0
## Environment
window10 & Google Chrome72.0.3626.109
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
1.build prod
2.run 
## What is expected?
good running
## What is actually happening?
error
## Other?

The toast.service.ts  build prod failure, mainly is the Toast._toastCompFactory = this._cfr.resolveComponentFactory(ToastComponent);
![image](https://user-images.githubusercontent.com/34148806/57190856-cf273c80-6f51-11e9-8578-901c01d3aa61.png)
![image](https://user-images.githubusercontent.com/34148806/57190871-ec5c0b00-6f51-11e9-88d3-0576e6ccdf93.png)

**Comment by Anberm** [comment]
@Guoyuanqiang I changed the way toast.ervice is exported and it works. I know the solution, but I fail to understand the cause of the problem

**Comment by fisherspy** [comment]
#440
