### ISSUE TITLE
doc modal & action-sheet demo error

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#414]
## Version
0.12.0
## Environment
window10 & Google Chrome72.0.3626.109
## Reproduction link
[https://stackblitz.com/edit/angular-pgjzxr?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-pgjzxr?file=src/app/app.component.ts)
## Steps to reproduce
1.run
## What is expected?
normal running
## What is actually happening?
error
## Other?
Forget to add their providers in the example,

**Comment by fisherspy** [comment]
#421
