### ISSUE TITLE
No provider for Toast

### ISSUE THREAD

**Issue by haoyinag** [NG-ZORRO/ng-zorro-antd-mobile#427]
## Version
0.12.0
## Environment
windows10  chrome
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
use Modal and Toast in component  , then get this error " No provider for Toast " even used "providers: [Toast, Modal]" 
## What is expected?
fix that ;
and how to use Toast or Modal in service or httpInterceptorProviders ???
## What is actually happening?
have no idea

**Comment by haoyinag** [comment]
@Guoyuanqiang ？？？

**Comment by fisherspy** [comment]
#440 已修复

**Comment by dusdong** [comment]
可以发个release吗？^_^  谢谢~  @fisherspy

**Comment by fisherspy** [comment]
@haoyinag @dusdong 0.12.1已经发布，请验证。
