### ISSUE TITLE
badge

### ISSUE THREAD

**Issue by imAcityman** [NG-ZORRO/ng-zorro-antd-mobile#437]
## Version
0.12.0
## Environment
ng7.2   zorro-mobile 0.12
## Reproduction link
[https://stackblitz.com/edit/angular-nabz8z-rgwlph](https://stackblitz.com/edit/angular-nabz8z-rgwlph)
## Steps to reproduce
badge的text双向绑定后，讲绑定的数据从0开始递增
## What is expected?
正确显示
## What is actually happening?
badge的位置显示出现bug
## Other?
如果双向绑定的数据从1开始递增，bug不会出现

**Comment by Guoyuanqiang** [comment]
close #441

**Comment by sWhite01111** [comment]
#441

**Comment by fisherspy** [comment]
@imAcityman  #446 应该已经修复，请验证。

**Comment by imAcityman** [comment]
@fisherspy 已验证，可以正确显示
