### ISSUE TITLE
IOS(12.1) 使用Picker组件，底部弹出选择框的颜色显示不正常

### ISSUE THREAD

**Issue by StarkL** [NG-ZORRO/ng-zorro-antd-mobile#438]
## Version
0.12.0
## Environment
苹果手机 IOS (12.1)
## Reproduction link
[https://stackblitz.com/edit/angular-hwzvck?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-hwzvck?file=src/app/app.component.ts)
## Steps to reproduce
1.打开官网Picker选择器；
2.有苹果手机扫码进入demo界面；

![image](https://user-images.githubusercontent.com/21234407/57506872-af1bc280-732f-11e9-944b-e8b58e5a45de.png)

3.点击任意Picker，即可看到bug。
## What is expected?
在苹果手机上能正常展示Picker
## What is actually happening?
跳出的Picker背景色异常，为灰色

![image](https://user-images.githubusercontent.com/21234407/57506770-6b28bd80-732f-11e9-81a9-53f47a9f0805.png)

**Comment by Guoyuanqiang** [comment]
该问题已修复，等待发布

**Comment by fisherspy** [comment]
@StarkL 0.12.1应该已经修复，请验证。
