### ISSUE TITLE
Grid可否提供一个属性来自定义项内容

### ISSUE THREAD

**Issue by visionding** [NG-ZORRO/ng-zorro-antd-mobile#439]
如题

**Comment by Guoyuanqiang** [comment]
@visionding 不知道你说的是不是这个 https://stackblitz.com/edit/angular-yn9g16?file=src/app/app.component.ts

**Comment by visionding** [comment]
@Guoyuanqiang 谢谢，这样应该可以实现。不过我看Grid的代码里面icon可以传TemplateRef，但是不知道怎么用

**Comment by Guoyuanqiang** [comment]
@visionding demo已经写好了。可以看看

**Comment by visionding** [comment]
@Guoyuanqiang 没有找到demo，可以发个地址吗？

**Comment by Guoyuanqiang** [comment]
@visionding 官网有demo呀 http://ng.mobile.ant.design/#/components/grid/zh
