### ISSUE TITLE
minDate，maxDate没有对应的例子吗？该怎么写

### ISSUE THREAD

**Issue by Octopus912** [NG-ZORRO/ng-zorro-antd-mobile#447]
<ListItem
    DatePicker
    [extra]="currentDateFormat(value, 'yyyy-mm-dd')"
    [arrow]="'horizontal'"
    [mode]="'date'"
   [minDate]="1900-01-01"
    [(ngModel)]="value"
    (onOk)="onOk($event)"
  >

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
上面写法会报错，可以更新例子吗

**Comment by fisherspy** [comment]
@Octopus912 麻烦提供stackblitz demo

**Comment by Octopus912** [comment]
DatePicker下面

 <List [className]="'date-picker-list'">
      <ListItem
        DatePicker
        [extra]="currentDateFormat(value2, 'yyyy-mm-dd')"
        [arrow]="'horizontal'"
        [mode]="'date'"
        [(ngModel)]="value2"
        (onOk)="onOk2($event)"
      >
        Date
        <Brief>{{ name2 }}</Brief>
      </ListItem>

    </List>

**Comment by fisherspy** [comment]
@Octopus912 需要提供stackblitz demo

**Comment by Guoyuanqiang** [comment]
@Octopus912 minDate不是字符串是日期。你这样写实字符串了。

**Comment by Octopus912** [comment]
那[minDate]= ？？？后面要写成什么格式

**Comment by Octopus912** [comment]
https://stackblitz.com/run

**Comment by Octopus912** [comment]
> @Octopus912 minDate不是字符串是日期。你这样写实字符串了。

希望可以更新一个[minDate]=？？ 的例子

**Comment by xuedongliu** [comment]
> @Octopus912 minDate不是字符串是日期。你这样写实字符串了。

我想请问一下，既然不是字符串。那么为什么在类型声明中定义为`maxDate: string`?

**Comment by liuliangjia** [comment]
到底怎么写的？
