### ISSUE TITLE
新建项目样式丢失

### ISSUE THREAD

**Issue by vinceok** [NG-ZORRO/ng-zorro-antd-mobile#457]
## Version
0.12.2
## Environment
见补充说明
## Reproduction link
[https://z7kb2a.run.stackblitz.io](https://z7kb2a.run.stackblitz.io)
## Steps to reproduce
新建一个项目，安装好依赖发现样式丢失，寻找原因无果，在StackBlitz上下载了官方的Button Demo到本地，也出现样式丢失的情况，但是在线的Demo又是正常的，目前不知道是何原因了。
## What is expected?
样式正常
## What is actually happening?
组件无样式
## Other?
Window：10
NPM：6.4.1
Angular CLI: 7.3.9
Node: 10.13.0
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9
@angular-devkit/core         7.3.9
@angular-devkit/schematics   7.3.9
@schematics/angular          7.3.9
@schematics/update           0.13.9
rxjs                         6.5.2
typescript                   3.2.4

**Comment by fisherspy** [comment]
有没有在angular.json里依赖ng-zorro-antd-mobile.min.css

**Comment by vinceok** [comment]
> 有没有在angular.json里依赖ng-zorro-antd-mobile.min.css

有引入，但无效。也测试了引入自定义主题，无效。你可以用我发的那个链接，把zip下载试下，最近把angular升级了，发现这情况，我也没回滚测试。

**Comment by vinceok** [comment]
初步可以判断是因为cnpm下载的ng-zorro包不完整导致的，angular.json里引ng-zorro-antd-mobile.min.css会找不到文件，解决办法是把ng-zorro-antd-mobile.min.css复制到项目中。或者使用theme.less，在顶部引入ng-zorro-antd-mobile.less
