### ISSUE TITLE
refactor popup service

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#459]
## What problem does this feature solve?
基于popup service，模态框 还是其他，都会受限于静态方法的单例modalRef ，针对复杂的场景，例如 下单选客户选商品选规格等多层嵌套的模态框使用，popup service 不能使用，而多个modal组件的使用 又会造成dom的卡顿，所以，我们也应该重构当前的服务 包含 弹出层的组件[modal drawer...]，参考于pc版的ng-zorro-antd https://ng.ant.design/components/modal/zh#components-modal-demo-service
## What does the proposed API look like?
页面能获取当前popup ref ，closeall, 少使用settimeout
https://ng.ant.design/components/modal/zh#components-modal-demo-service

**Comment by fisherspy** [comment]
@Anberm 1.0.0-beta.0出来了，看看是否解决问题。

**Comment by Anberm** [comment]
> @Anberm 1.0.0-beta.0出来了，看看是否解决问题。

可以了，谢谢
