### ISSUE TITLE
antd-mobile样式侵入太严重

### ISSUE THREAD

**Issue by vinceok** [NG-ZORRO/ng-zorro-antd-mobile#464]
## Version
0.11.2
## Environment
Window：10 NPM：6.4.1 Angular CLI: 7.3.9 Node: 10.13.0 OS: win32 x64
## Reproduction link
[https://z7kb2a.run.stackblitz.io](https://z7kb2a.run.stackblitz.io)
## Steps to reproduce
项目中使用了部分组件，例如图片上传，Textarea，Modal等等，发现样式侵入严重，例如图片上传组件内置margin，影响到开发者项目内的布局，这不是一个框架应该做的事。同样的问题出现在Textarea上。Modal组件更深，整体颜色被设置。总之，很多类似问题，希望能仔细检查，并进行优化。
## What is expected?
n/a
## What is actually happening?
n/a
## Other?
n/a

**Comment by fisherspy** [comment]
Angular和React版本是复用一套样式库，因此在组件研发过程中，组件的封装类型为None。业务代码里需要将页面或组件的封装类型至少设置为emulated。

**Comment by vinceok** [comment]
> Angular和React版本是复用一套样式库，因此在组件研发过程中，组件的封装类型为None。业务代码里需要将页面或组件的封装类型至少设置为emulated。

您所说的封装类型可设置吗？文档里并没有相关说明

**Comment by fisherspy** [comment]
@vinceok 组件库没有用封装是为了复用antd 整体样式库，所以你们需要在业务代码里将业务component的encapsulation设置为emulated，然后在scss中使用:host的写法，让你们自己的业务样式优先使用。
