### ISSUE TITLE
InputItem组件，在手机上每次输入，光标会自动被移至末尾

### ISSUE THREAD

**Issue by artemisXiao** [NG-ZORRO/ng-zorro-antd-mobile#465]
## Version
0.12.2
## Environment
IOS 10.2.1 ～ 12.3.1
## Reproduction link
[https://mj9g3t.run.stackblitz.io](https://mj9g3t.run.stackblitz.io)
## Steps to reproduce
不含[moneyKeyboardAlign]属性的inputItem，在手机上输入几个字符后，把光标移至input的最前面(只要不在最后)，输入任何字符，光标将被set到input的最末尾
## What is expected?
我在最前面输入，光标应该保持在我输入的字符的后面
## What is actually happening?
光标被set到input的最末尾
## Other?
input普通的输入场景，当用户输错值或者想在前面或中间插入字符

**Comment by dusdong** [comment]
我也遇到这个问题

**Comment by sWhite01111** [comment]
#500
