### ISSUE TITLE
ImagePicker pick more than 15 pictrues over 6M, adding and deleting very slowly.

### ISSUE THREAD

**Issue by hackeryutu** [NG-ZORRO/ng-zorro-antd-mobile#468]
## Version
0.11.7
## Environment
Browser Version 74.0.3729.169 (Official Build) (64-bit)、 ng-zorro-antd-mobile 0.11.7
## Reproduction link
[https://oznra1.run.stackblitz.io](https://oznra1.run.stackblitz.io)
## Steps to reproduce
Pick more than 15 pictrues over 6M, adding and deleting very slowly.
## What is expected?
fast
## What is actually happening?
slow

**Comment by fisherspy** [comment]
@hackeryutu 请问是用桌面浏览器还是手机？

**Comment by fisherspy** [comment]
长时间未收到反馈，暂时关闭。
