### ISSUE TITLE
PullToRefresh   Accordion 苹果设备会出现闪烁现象

### ISSUE THREAD

**Issue by haoyk** [NG-ZORRO/ng-zorro-antd-mobile#473]
## Version
0.12.2
## Environment
0.12.2
## Reproduction link
[https://stackblitz.com/github/haoyk/ant_demo](https://stackblitz.com/github/haoyk/ant_demo)
## Steps to reproduce
如重现链接
## What is expected?
正常刷新
## What is actually happening?
刷新时有闪烁

**Comment by fisherspy** [comment]
@haoyk 能更新一下stackblitz demo吗？运行不起来

**Comment by fisherspy** [comment]
更新依赖后的demo地址：https://stackblitz.com/edit/github-zqdm2b

**Comment by fisherspy** [comment]
1.0.0-beta.2版本在iOS12.4.1版本的safari中没有出现该问题。
