### ISSUE TITLE
PickerView 组件没有onPickerChange回调函数

### ISSUE THREAD

**Issue by huashaoZhao** [NG-ZORRO/ng-zorro-antd-mobile#475]
## What problem does this feature solve?
用onPickerChange这个函数可以处理列之间的相互控制
## What does the proposed API look like?
返回值
EventEmitter<any[]>

**Comment by Guoyuanqiang** [comment]
@huashaoZhao ngModelChange不能满足吗？

**Comment by fisherspy** [comment]
@huashaoZhao 太久没有回复了，暂时关闭该issue。
