### ISSUE TITLE
SwipeAction组件用*ngFor之后左右滑动不生效

### ISSUE THREAD

**Issue by huashaoZhao** [NG-ZORRO/ng-zorro-antd-mobile#478]

**Comment by fisherspy** [comment]
@huashaoZhao 请按标准填写issue，并提供stackblitz demo

**Comment by BronzeCui** [comment]
https://stackblitz.com/edit/angular-ifs3su?file=src/app/app.component.ts

**Comment by fisherspy** [comment]
长时间未收到反馈，暂时关闭。
