### ISSUE TITLE
Accordion手风琴展开无法自动展开面板，滚动条不自动滚动

### ISSUE THREAD

**Issue by oceanxue** [NG-ZORRO/ng-zorro-antd-mobile#480]
## Version
0.12.3
## Environment
IOS
## Reproduction link
[https://stackblitz.com/edit/angular-svgt9e?file=src/app/app.component.ts](https://stackblitz.com/run)
## Steps to reproduce
Accordion放置画面最下面，点击展开后IE滚动条不跟随滚动到画面最下方，手风琴内容需要手动滚动查看。
## What is expected?
自动滚动

**Comment by fisherspy** [comment]
@oceanxue demo这个地址是无效的

**Comment by fisherspy** [comment]
@Guoyuanqiang 官网手机demo最后一条确实会出现这种情况。

**Comment by fisherspy** [comment]
@oceanxue inactive: true设置后会点击不展开，官网没问题。

**Comment by BronzeCui** [comment]
#575 解决手风琴模式下无法自动展开的问题，点击滚动到屏幕中可以在组件外层做
