### ISSUE TITLE
加入了模块延迟加载后生产环境中项目会报错  project will report an error if module is lazy loaded in production environment.

### ISSUE THREAD

**Issue by dodobelieve** [NG-ZORRO/ng-zorro-antd-mobile#484]
## Version
0.12.5
## Environment
production environment
## Reproduction link
[https://stackblitz.com/edit/angular-kyf8af](https://stackblitz.com/edit/angular-kyf8af)
## Steps to reproduce
after add lazy loaded module, project works fine in development environment, but report error while uploading to production environment.
项目加入了模块延迟加载后，开发环境正常，生产环境报错
## What is expected?
 works fine in development environment too.
## What is actually happening?
report error in production environment.

**Comment by fisherspy** [comment]
这需要组件库升级到Angular 8，目前还是支持7.x。
