### ISSUE TITLE
为什么modal和toast的调用的都是静态方法，而不是实例方法呢？

### ISSUE THREAD

**Issue by fengbaozhiling** [NG-ZORRO/ng-zorro-antd-mobile#485]
## Version
0.12.5
## Environment
chrome
## Reproduction link
[https://bg53pv.run.stackblitz.io](https://bg53pv.run.stackblitz.io)
## Steps to reproduce
使用modal多次，然后冲突了，无法多个modal共存
## What is expected?
多个modal共存
## What is actually happening?
只能有一个实例
## Other?
期望使用实例方法调用

**Comment by Guoyuanqiang** [comment]
@fengbaozhiling 会重构，期待下一版本
