### ISSUE TITLE
Steps 图标显示不全

### ISSUE THREAD

**Issue by lty87** [NG-ZORRO/ng-zorro-antd-mobile#489]
官方示例中，this.steps放在OnInit中，显示一切正常
ngOnInit() {
    this.steps = [
      {
        title: 'Finished000',
        description: 'This is description'
      },
      {
        title: 'In Progress',
        description: 'This is description'
      },
      {
        title: 'Waiting',
        description: 'This is description'
      }
    ];
  }

我的项目中，静态数据图标显示正常，但是从接口访问的数据，放在constructor中也正常，放在OnInit中数据能显示出来，但是图标不能正常显示，都是显示的圈圈。svg没有正常加载 。

**Comment by sWhite01111** [comment]
能提供一个复现的demo么
