### ISSUE TITLE
navbar Icon and font are not vertically aligned

### ISSUE THREAD

**Issue by nuonuoge** [NG-ZORRO/ng-zorro-antd-mobile#49]
**Version**
0.9.5
**Environment**
win10
**Reproduction link**
http://ng.mobile.ant.design/#/components/nav-bar/zh
**Steps to reproduce**
http://ng.mobile.ant.design/#/components/nav-bar/zh this demo navbar Icon and font are not vertically aligned
**What is expected?**
navbar Icon and font are vertically aligned
**What is actually happening?**
navbar Icon and font are not vertically aligned
**Other**
![2018-10-15_172638](https://user-images.githubusercontent.com/16378798/46942288-9734d680-d09f-11e8-93f8-eb7ad64d2353.png)

I see noticebar component use css
```
noticebar icon {
  display: flex;
}
```
can I make a pull request to navbar
like noticebar,I will add addon.less
```
navbar, nzm-nav-bar {
  display: flex;
}
```
or 

```
.am-navbar-left, .am-navbar-right {
  display: flex;
}
```

**Comment by 3fuyu** [comment]
@nuonuoge it works #47

**Comment by nuonuoge** [comment]
ok
