### ISSUE TITLE
ToastService.info()放在组件ngOnInit()中会报错

### ISSUE THREAD

**Issue by dodobelieve** [NG-ZORRO/ng-zorro-antd-mobile#495]
## Version
0.12.5
## Environment
开发环境
## Reproduction link
[https://stackblitz.com/edit/angular-ycacfp](https://stackblitz.com/edit/angular-ycacfp)
## Steps to reproduce
将ToastService.info()放在组件的ngOnInit()中就会报错（ERROR Error: ApplicationRef.tick is called recursively）
## What is expected?
能够正常运行
## What is actually happening?
报错，提示信息不能正确显示

**Comment by dodobelieve** [comment]
ToastService的另外几个方法也有同样的问题

**Comment by Guoyuanqiang** [comment]
@dodobelieve 如果是在ngOnInit()中调用，用settimeout包一下即可
