### ISSUE TITLE
InputItem 在editable为false的情况下，ios依然有软键盘响应

### ISSUE THREAD

**Issue by DeMeng33** [NG-ZORRO/ng-zorro-antd-mobile#496]
## Version
0.12.5
## Environment
ios
## Steps to reproduce
``` typescript
<InputItem [editable]="false" [labelNumber]="6“ [value]="‘123'">row</InputItem>
```
尽管input被禁用了但是ios下仍会触发软键盘，显示“完成”按钮
![错误图片](http://demeng-pic.oss-cn-beijing.aliyuncs.com/WeChat7394e874e0d91cb660257fdee3642121.png)
## What is expected?
不可编辑，没有软键盘
## What is actually happening?
虽然不可编辑，但是出现了软键盘 “完成按钮”

**Comment by sWhite01111** [comment]
#500
