### ISSUE TITLE
The disabled property of the button component is invalid

### ISSUE THREAD

**Issue by ChaoQunPeng** [NG-ZORRO/ng-zorro-antd-mobile#504]
## Version
0.12.5
## Environment
Angular CLI: 8.0.6   Node: 10.15.3
## Reproduction link
[https://stackblitz.com/edit/angular-vcnhig?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-vcnhig?file=src/app/app.component.ts)
## Steps to reproduce
This button is disabled but still executes when clicked
## What is expected?
Methods cannot be executed when the button sets disabled
## What is actually happening?
Methods can be executed when the button sets disabled

**Comment by Guoyuanqiang** [comment]
@ChaoQunPeng 你提供的链接disabled是没有click响应的
![image](https://user-images.githubusercontent.com/6535259/61805752-f4e52300-ae68-11e9-9ccf-4ade819c8bf0.png)
