### ISSUE TITLE
ng-zorro-antd-mobile/components/modal/modal.component.ts

### ISSUE THREAD

**Issue by zhulj** [NG-ZORRO/ng-zorro-antd-mobile#505]
ng-zorro-antd-mobile/components/modal/modal.component.ts
visiable 属性没有加@Input()  无法 修改

**Comment by Guoyuanqiang** [comment]
@zhulj visiable已废弃，请参考官网demo：https://stackblitz.com/edit/angular-th99a6?file=src/app/app.component.ts
