### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by agedream** [NG-ZORRO/ng-zorro-antd-mobile#506]
## Version
0.12.5
## Environment
Win10    Webstorm
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
根据官网快速上手操作命令创建项目，到编译时出错。执行的命令
1.ng new mobile-test
2.ng add ng-zorro-antd-mobile
3.ng build --prod
## What is expected?
项目打包成功。
## What is actually happening?
控制台编译报错，以下是错误信息：
C:\Users\asdad\mobile-test>ng build --prod

chunk {0} runtime-es2015.703a23e48ad83c851e49.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.efedd750490b14de3f18.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es2015.66a9e684cc8ebe117187.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.dd84567063797ed6e0cb.css (styles) 149 kB [initial] [rendered]
Date: 2019-07-18T08:03:15.152Z - Hash: 7eee61d1578715a1dfc8 - Time: 5732ms

ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(18,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
## Other?
重现地址乱填的，因为创建项目到编译从未写过一行代码。

**Comment by Iixianjie** [comment]
`ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signa
tures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(18,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
`

遇到同样的问题😣

**Comment by fisherspy** [comment]
> `ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signa tures. node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(18,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures. `
> 
> 遇到同样的问题😣

@agedream @Iixianjie 请使用ng7的ci试试，我们暂时还没有升级到ng8。

**Comment by fisherspy** [comment]
@agedream @Iixianjie 1.0.0-beta.1已支持Angular 8

**Comment by love-YY** [comment]
> @agedream @Iixianjie 1.0.0-beta.1已支持Angular 8
当前使用ng build --prod 还是有问题： ng version 8.2.3
ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,106): Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(19,106): Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.

**Comment by ccjhpu** [comment]
我也是同样的报错，我的版本是 "ng-zorro-antd-mobile": "^1.0.0-beta.1",
"@angular/cli": "8.3.2",  请教大家有好的解决方案吗

**Comment by fisherspy** [comment]
@love-YY @ccjhpu @agedream @Iixianjie 1.0.0-beta.2修复了这个错误

**Comment by agreadname** [comment]
@fisherspy 你好，我用的是    "@angular/cli": "~7.3.8",版本，    "ng-zorro-antd-mobile": "^0.12.5",
ngc aot 编译打包就报这个错误
`..\..\node_modules\ng-zorro-antd-mobile\ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.`
