### ISSUE TITLE
什么时候能提供Angular8的支持

### ISSUE THREAD

**Issue by xinzheng22** [NG-ZORRO/ng-zorro-antd-mobile#507]
什么时候能提供Angular8的支持

**Comment by DreamPWJ** [comment]
8月

**Comment by xindalu** [comment]
期待啊，请问8月初还是8月底？

**Comment by harrylyh** [comment]
ionic已经支持angular8了，不知道具体支持时间是什么时候？最近有项目要启动

**Comment by fisherspy** [comment]
9月份

**Comment by fisherspy** [comment]
@xinzheng22 @harrylyh @xindalu 1.0.0-beta.1已支持Angular 8

**Comment by harrylyh** [comment]
> @xinzheng22 @harrylyh @xindalu 1.0.0-beta.1已支持Angular 8

非常棒，给力

**Comment by xindalu** [comment]
ng builld --prod还是报错呢？
`ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,106): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(19,106): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.`

**Comment by harrylyh** [comment]
> > @xinzheng22 @harrylyh @xindalu 1.0.0-beta.1已支持Angular 8
> 
> 非常棒，给力

![image](https://user-images.githubusercontent.com/26681969/64240916-5bb02e80-cf35-11e9-9ce6-5b5309231517.png)
我的也是啊

**Comment by harrylyh** [comment]
> > > @xinzheng22 @harrylyh @xindalu 1.0.0-beta.1已支持Angular 8
> > 
> > 
> > 非常棒，给力
> 
> ![image](https://user-images.githubusercontent.com/26681969/64240916-5bb02e80-cf35-11e9-9ce6-5b5309231517.png)
> 我的也是啊

还没有在组件里面用，只是在根模块中引入了NgZorroAntdMobileModule就打包不过去

**Comment by harrylyh** [comment]
> > > > @xinzheng22 @harrylyh @xindalu 1.0.0-beta.1已支持Angular 8
> > > 
> > > 
> > > 非常棒，给力
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26681969/64240916-5bb02e80-cf35-11e9-9ce6-5b5309231517.png)
> > 我的也是啊
> 
> 还没有在组件里面用，只是在根模块中引入了NgZorroAntdMobileModule就打包不过去

没有加 --prod是可以的，加了就报错

**Comment by fisherspy** [comment]
@xindalu @harrylyh 1.0.0-beta.2修复了这个错误

**Comment by xindalu** [comment]
O了，多谢！
