### ISSUE TITLE
使用 ci 部署项目时报错

### ISSUE THREAD

**Issue by hqwlkj** [NG-ZORRO/ng-zorro-antd-mobile#512]
## Version
0.12.5
## Environment
  
![image](https://user-images.githubusercontent.com/12181423/61936969-65528800-afc0-11e9-89f2-c02e9aa57f27.png)

## Reproduction link
![image](https://user-images.githubusercontent.com/12181423/61937005-7a2f1b80-afc0-11e9-84fc-8f27c37e256c.png)

## Steps to reproduce
“”
## What is expected?
“”
## What is actually happening?
“”

**Comment by fisherspy** [comment]
@hqwlkj 请先使用ng7的ci试试，我们暂时还没升级到ng8

**Comment by hqwlkj** [comment]
@hqwlkj  好的，谢谢

**Comment by Iurmy** [comment]
我也碰见了，就把那个TemplateRef<any> 改成 any ，ng8的cli就能用了。

**Comment by hqwlkj** [comment]
@Iurmy   你是 fork 之后在安装的吗？

**Comment by Iurmy** [comment]
> @Iurmy 你是 fork 之后在安装的吗？

不是，ng8的话还是暂时别用了，Carousel组件也有问题，手动轮播时infinite参数没用，不能禁止循环轮播，鬼知道还有什么坑。

**Comment by hqwlkj** [comment]
@Iurmy  哦 好的谢谢

**Comment by liuliangjia** [comment]
ng new testProject --version 7.1.0

**Comment by fisherspy** [comment]
> 

你可以在package.json 里修改ng版本
