### ISSUE TITLE
<Tab>设定为垂直时,<tab页的content>嵌套<carousel>时. carousel,会把tab的content部分宽度撑开.使得content页面向右溢出viewport

### ISSUE THREAD

**Issue by zsq2010** [NG-ZORRO/ng-zorro-antd-mobile#514]
## Version
0.12.5
## Environment
应该是所有浏览器.(主要是在ios和chrome上),
## Reproduction link
[https://angular-u4wn1h.stackblitz.io](https://angular-u4wn1h.stackblitz.io)
## Steps to reproduce
1.准备一个carousel  https://hcb616.run.stackblitz.io 2.准备一个垂直样式tab https://g4ymvd.run.stackblitz.io  3.把carousel放进tab第一标签
## What is expected?
carousel,能正确完整显示(显示宽度)
## What is actually happening?
carousel导致tab内容被向右拉的更宽,超出界面.
## Other?
grid的carousel模式,应该也是借用carousel模块. 所以,也存在这样的问题

**Comment by fisherspy** [comment]
在1.0.0-beta.0版本中，carousel能完整显示。但是extra与dot位置不对。仍需继续排查。

**Comment by fisherspy** [comment]
https://stackblitz.com/edit/angular-u4wn1h-3urkok @zsq2010 给ima指定个高度就好了。
