### ISSUE TITLE
Calender组件使用效果在手机上与预期的结果不一致

### ISSUE THREAD

**Issue by iamzhangxin** [NG-ZORRO/ng-zorro-antd-mobile#519]
## Version
0.12.5
## Environment
PC(Chrome 75.0.3770.142)、 Android/iOS(Ionic4)
## Reproduction link
[https://stackblitz.com/github/gqaiyaxr](https://stackblitz.com/github/gqaiyaxr)
## Steps to reproduce
在Ionic上使用Ng-Zorro-Mobile日历组件在手机上的显示效果有问题
1、直接在PC上启动ionic serve，在浏览器中查看效果一切正常，见期望的结果是什么
2、使用ionic cordova prepare ios打包并安装在手机上之后，显示效果错误，见实际的结果
## What is expected?
<img src="https://minicoralcommon.oss-cn-zhangjiakou.aliyuncs.com/apppicture/pc%3Achrome.png" width="50%">

## What is actually happening?
<img src="https://minicoralcommon.oss-cn-zhangjiakou.aliyuncs.com/apppicture/ios.PNG" width="50%">
## Other?
感觉在手机上就是，上面标题的地方完全被遮挡了。请问有没有解决方案

**Comment by 3fuyu** [comment]
需要提供下可复现的环境

**Comment by fisherspy** [comment]
> 需要提供下可复现的环境

看描述是ionic cordova prepare ios打包环境里出错

**Comment by iamzhangxin** [comment]
> > 需要提供下可复现的环境
> 
> 看描述是ionic cordova prepare ios打包环境里出错

请问是哪里出的错呢，能告知下么

**Comment by fisherspy** [comment]
> > > 需要提供下可复现的环境
> > 
> > 
> > 看描述是ionic cordova prepare ios打包环境里出错
> 
> 请问是哪里出的错呢，能告知下么

你能拿到cordova环境的错误信息吗？

**Comment by iamzhangxin** [comment]
Cordova没有保存。正常打包通过了。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: >°))))彡 <notifications@github.com>
发送时间: Thursday, August 29, 2019 8:24:06 PM
收件人: NG-ZORRO/ng-zorro-antd-mobile <ng-zorro-antd-mobile@noreply.github.com>
抄送: ZhangXin <minicoral@outlook.com>; Author <author@noreply.github.com>
主题: Re: [NG-ZORRO/ng-zorro-antd-mobile] Calender组件使用效果在手机上与预期的结果不一致 (#519)


需要提供下可复现的环境

看描述是ionic cordova prepare ios打包环境里出错

请问是哪里出的错呢，能告知下么

你能拿到cordova环境的错误信息吗？

―

**Comment by fisherspy** [comment]
@iamzhangxin 你提供的demo出了问题，能再次提供下demo吗？你是说现在cordova打包没问题了？

**Comment by iamzhangxin** [comment]
是这样的Cordova打包一直没有报错，我现在借了朋友手机发现，有的手机正常。有的不正常。感觉跟屏幕高度什么的有关系。这俩是同一套代码。不正常的是ios正常的是安卓。但是小屏安卓也不正常。很诡异。
[Image][Image]

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: >°))))彡 <notifications@github.com>
发送时间: 星期四, 八月 29, 2019 20:26
收件人: NG-ZORRO/ng-zorro-antd-mobile
抄送: ZhangXin; Mention
主题: Re: [NG-ZORRO/ng-zorro-antd-mobile] Calender组件使用效果在手机上与预期的结果不一致 (#519)


@iamzhangxin<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiamzhangxin&data=02%7C01%7C%7C504644d23fd2438348ec08d72c7c1f45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637026783917875065&sdata=4zdta84BM5csA7ebjBK80l32QwFebZQhz41e6WFJd9o%3D&reserved=0> 你提供的demo出了问题，能再次提供下demo吗？你是说现在cordova打包没问题了？

―

**Comment by fisherspy** [comment]
@iamzhangxin 你提供的图片看不到。

**Comment by fisherspy** [comment]
@iamzhangxin 最新版的ionic上看看是否OK了？

**Comment by 3fuyu** [comment]
> 是这样的Cordova打包一直没有报错，我现在借了朋友手机发现，有的手机正常。有的不正常。感觉跟屏幕高度什么的有关系。这俩是同一套代码。不正常的是ios正常的是安卓。但是小屏安卓也不正常。很诡异。 [Image][Image] 获取 Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ 发件人: >°))))彡 <notifications@github.com> 发送时间: 星期四, 八月 29, 2019 20:26 收件人: NG-ZORRO/ng-zorro-antd-mobile 抄送: ZhangXin; Mention 主题: Re: [NG-ZORRO/ng-zorro-antd-mobile] Calender组件使用效果在手机上与预期的结果不一致 (#519) @iamzhangxin<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiamzhangxin&data=02%7C01%7C%7C504644d23fd2438348ec08d72c7c1f45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637026783917875065&sdata=4zdta84BM5csA7ebjBK80l32QwFebZQhz41e6WFJd9o%3D&reserved=0> 你提供的demo出了问题，能再次提供下demo吗？你是说现在cordova打包没问题了？ ― You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNG-ZORRO%2Fng-zorro-antd-mobile%2Fissues%2F519%3Femail_source%3Dnotifications%26email_token%3DACLXFBTDA5VEO6Z2K4OOCI3QG657LA5CNFSM4IJ4A7I2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5OJPTA%23issuecomment-526161868&data=02%7C01%7C%7C504644d23fd2438348ec08d72c7c1f45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637026783917885070&sdata=RvfQ2ND0zJFlcpPILfLfj3mHcm3%2FsW39%2FqtlMXh2d3w%3D&reserved=0>, or mute the thread<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACLXFBTXKOPAZSPQBNICZITQG657LANCNFSM4IJ4A7IQ&data=02%7C01%7C%7C504644d23fd2438348ec08d72c7c1f45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637026783917895081&sdata=VPVjnyfSOqVo22vNclQhs36%2BYaFbf%2B2mhsNL3pqkTwI%3D&reserved=0>.

手机兼容性问题建议检查是否给够足够的容器高度

**Comment by fisherspy** [comment]
@iamzhangxin 因为7天没有回复，暂时关闭该issue。如果还是复现，请reopen。
