### ISSUE TITLE
文本输入框,内容如果用双向绑定时,setCls可能会因为初始化时没有值导致方法跳过

### ISSUE THREAD

**Issue by HungryBunny-wei** [NG-ZORRO/ng-zorro-antd-mobile#525]
## Version
0.12.5
## Environment
移动端
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-nv1mxd](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-nv1mxd)
## Steps to reproduce
用移动端访问,
第一个手风琴没有问题,(似乎是因为设置了默认展开的原因)
第二个手风琴,输入框label没有对应的class,(am-input-label-5, 可能的原因是因为内容文本是单向绑定setCls方法判断没有文本就不设置类)
## What is expected?
设置labelNumber="5"对应的class也要有
## What is actually happening?
设置labelNumber="5"如果手风琴没有默认展开,会少了class="am-input-label-5"
## Other?
本人再移动端才发现这个bug,浏览器没调试出来,但是看stackblitz上很明显label少了样式

不能弄个编辑器来填写问题啊T.T.https://ng.mobile.ant.design/issue-helper

**Comment by HungryBunny-wei** [comment]
![image](https://user-images.githubusercontent.com/28952169/62933466-d1bcec00-bdf4-11e9-9c6d-1922a0ea5515.png)
这里补充上图

**Comment by nuonuoge** [comment]
panel里面使用了ng-content导致的，ng-contnet在编译时完成，它只是移动元素，投影内容的生命周期绑定到了它被声明的地方，所以使用了ngIf没起到作用
![image](https://user-images.githubusercontent.com/16378798/63016289-dc938180-bec5-11e9-940f-822b0c762e07.png)

**Comment by sWhite01111** [comment]
#527 新增了一个api content来解决这个问题，同时也支持了需要自定义label的情况，你可以这样写
<nzm-input-item type="text" placeholder="文本输入框" [labelNumber]="5" [content]="label">
  </nzm-input-item>

**Comment by HungryBunny-wei** [comment]
> [＃527](https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/527)新增了一个api content来解决这个问题，同时也支持了需要自定义label的情况，你可以这样写
> <nzm-input-item type =“text”placeholder =“文本输入框”[labelNumber] = “5”[content] =“label”>

这种方式不好吧,和以前的操作会变化有点大,
个人建议是不是这段可以不要
![image](https://user-images.githubusercontent.com/28952169/63089090-5771a080-bf89-11e9-8582-09ec981c015c.png)

**Comment by sWhite01111** [comment]
这段不能不要，有其他逻辑的。加这个content api还是会兼容之前写法的；只不过放到手风琴里的会比较特殊，所以支持了这个api，我和写手风琴的同学商量后觉得这个方法是最可行的

**Comment by sWhite01111** [comment]
在手风琴里只是变化了一种写法，对操作没有什么影响

**Comment by fisherspy** [comment]
#527 引入breaking change

**Comment by fisherspy** [comment]
@HungryBunny-wei 1.0.0-beta.0出来了，你使用content api替代老的写法就可以了。
