### ISSUE TITLE
ng build --prod报错了

### ISSUE THREAD

**Issue by qqaimh** [NG-ZORRO/ng-zorro-antd-mobile#526]
按照你们官网上的”快速上手“操作一步一步的，报错如下
E:\AobAnt> ng build --prod

chunk {0} runtime-es2015.5bc68c0dd8cf137fbe82.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.183ed7617498f12a2818.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es2015.0cf243708f568e3b249e.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.dd84567063797ed6e0cb.css (styles) 149 kB [initial] [rendered]
Date: 2019-08-14T04:56:36.793Z - Hash: 64ca69063fe248b43614 - Time: 4481ms

**ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(18,48): Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.**

我用的"@angular/cli": "~8.2.1",

**Comment by fisherspy** [comment]
@qqaimh 我们正在升级到ng8.0，目前在ng8.0上会出现这种问题。

**Comment by fisherspy** [comment]
@qqaimh 1.0.0-beta.1已支持Angular 8

**Comment by bcddh** [comment]
> @qqaimh 1.0.0-beta.1已支持Angular 8

仍然报这个错误。
"@angular/animations": "~8.2.0",
"@angular/common": "~8.2.0",
"@angular/compiler": "~8.2.0",
"@angular/core": "~8.2.0",
"ng-zorro-antd-mobile": "^1.0.0-beta.1",

**Comment by qqaimh** [comment]
> > @qqaimh 1.0.0-beta.1已支持Angular 8
> 
> 仍然报这个错误。
> "@angular/animations": "~8.2.0",
> "@angular/common": "~8.2.0",
> "@angular/compiler": "~8.2.0",
> "@angular/core": "~8.2.0",
> "ng-zorro-antd-mobile": "^1.0.0-beta
我还没有试

**Comment by fisherspy** [comment]
@qqaimh 1.0.0-beta.2修复了这个错误

**Comment by qqaimh** [comment]
> @qqaimh 1.0.0-beta.2修复了这个错误
好好，这个月工资加倍
