### ISSUE TITLE
惰性加载无法使用button元素

### ISSUE THREAD

**Issue by enddering** [NG-ZORRO/ng-zorro-antd-mobile#53]
## Version
0.9.5
## Environment
ng 惰性加载
## Reproduction link
[https://stackblitz.com/edit/angular-ubvhjn](https://stackblitz.com/edit/angular-ubvhjn)
## Steps to reproduce
点击Customers
## What is expected?
惰性加载可以使用相关元素，希望有相关惰性加载的用例可测试
## What is actually happening?
未知
## Other?
暂时只是测试button元素，其他的在惰性加载是否可用未知。

**Comment by cdllqos** [comment]
@enddering  U have to import 'ng-zorro-antd-mobile' in the child moudle,like this:
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CustomersRoutingModule } from './customers-routing.module';
import { CustomerListComponent } from './customer-list/customer-list.component';
import { NgZorroAntdMobileModule } from 'ng-zorro-antd-mobile';
@NgModule({
  imports: [
    CommonModule,
    CustomersRoutingModule,
    NgZorroAntdMobileModule
  ],
  declarations: [CustomerListComponent]
})
export class CustomersModule { }


/*
Copyright 2017-2018 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/
```

**Comment by enddering** [comment]
> @enddering U have to import 'ng-zorro-antd-mobile' in the child moudle,like this:
> 
> ```ts
> import { NgModule } from '@angular/core';
> import { CommonModule } from '@angular/common';
> import { CustomersRoutingModule } from './customers-routing.module';
> import { CustomerListComponent } from './customer-list/customer-list.component';
> import { NgZorroAntdMobileModule } from 'ng-zorro-antd-mobile';
> @NgModule({
>   imports: [
>     CommonModule,
>     CustomersRoutingModule,
>     NgZorroAntdMobileModule
>   ],
>   declarations: [CustomerListComponent]
> })
> export class CustomersModule { }
> 
> 
> /*
> Copyright 2017-2018 Google Inc. All Rights Reserved.
> Use of this source code is governed by an MIT-style license that
> can be found in the LICENSE file at http://angular.io/license
> */
> ```

not working
https://stackblitz.com/edit/angular-ubvhjn

![20181016-140518](https://user-images.githubusercontent.com/16018453/46996740-53e67080-d150-11e8-96e0-2a5b97e96a22.png)

**Comment by cdllqos** [comment]
please remove p tag, and then try it

**Comment by enddering** [comment]
> @enddering please remove p tag, and then try it

it's running, but, why?
