### ISSUE TITLE
InputItem文本输入框  onChang()事件获取不到手写输入的文字 

### ISSUE THREAD

**Issue by Zwei-J** [NG-ZORRO/ng-zorro-antd-mobile#532]
手写输入文字进去文本框上是显示了 但是在做判断的时候手写输入的文字是识别不到的 value为undefined 这个怎么解决？

**Comment by fisherspy** [comment]
@Zwei-J 你先按issue规范改一下格式，提供一个stackblitz demo吧

**Comment by Zwei-J** [comment]
import { Component } from '@angular/core';
import { ToastService } from 'ng-zorro-antd-mobile';

@Component({
  selector: 'demo-input-item-basic',
  template: `
    <TextareaItem [placeholder]="'请输入'"
              [autoFocus]="true"
              [value]="value"
              [clear]="true"
              [autoHeight]="true"
              (onChange)="onChange($event)"
></TextareaItem>
<WingBlank>
  <Flex>
    <FlexItem>
      <div Button [type]="'primary'" (onClick)="onClick()">提交</div>
    </FlexItem>
  </Flex>
</WingBlank>
  `,
  styles: [``]
})
export class DemoInputItemBasicComponent {
  value: string;

  constructor(private _toast: ToastService) {}

 onChange(e) {
    e = e.replace(/(^\s*)|(\s*$)/g, '');
    this.value = e;
  };

  onClick() {
    if ( this.value !== undefined && this.value !== '') {
      ToastService.success('我是拼音输入', 1000);
    } else {
      ToastService.fail('我是手写输入', 1000);
    }
  };
}
// 用手机的手写功能才能测试出来 偶然发现 谢谢

**Comment by Zwei-J** [comment]
> @ Zwei-J你先按问题规范改一下格式，提供一个stackblitz demo吧
`import { Component } from '@angular/core';
import { ToastService } from 'ng-zorro-antd-mobile';

@Component({
  selector: 'demo-input-item-basic',
  template: `
    <TextareaItem [placeholder]="'请输入'"
              [autoFocus]="true"
              [value]="value"
              [clear]="true"
              [autoHeight]="true"
              (onChange)="onChange($event)"
></TextareaItem>
<WingBlank>
  <Flex>
    <FlexItem>
      <div Button [type]="'primary'" (onClick)="onClick()">提交</div>
    </FlexItem>
  </Flex>
</WingBlank>
  `,
  styles: [``]
})
export class DemoInputItemBasicComponent {
  value: string;

  constructor(private _toast: ToastService) {}

 onChange(e) {
    e = e.replace(/(^\s*)|(\s*$)/g, '');
    this.value = e;
  };

  onClick() {
    if ( this.value !== undefined && this.value !== '') {
      ToastService.success('我是拼音输入', 1000);
    } else {
      ToastService.fail('我是手写输入', 1000);
    }
  };
}`

**Comment by sWhite01111** [comment]
能提供一下复现的手机系统型号和系统版本么，我这里没有复现出来

**Comment by fisherspy** [comment]
@Zwei-J

**Comment by Zwei-J** [comment]
安卓系统的手机但是具体机型我这边也不记得了 我们用比较常用的安卓机试了也重现不出来

**Comment by fisherspy** [comment]
> 安卓系统的手机但是具体机型我这边也不记得了 我们用比较常用的安卓机试了也重现不出来

那暂时关闭，等你有了准确的复现路径再reopen。

**Comment by Zwei-J** [comment]
我这边收集了几个机型出现这样的问题
1、vivo y66iA
2、小米 MDE6S
3、华为 mt7-tl10
4、vivo Y79A
5、lephone

**Comment by Zwei-J** [comment]
@fisherspy @sWhite01111
