### ISSUE TITLE
Modal 示例里的secure-text、login-password出现异常

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#542]
## Version
1.0.0-beta.0
## Environment
win10 Google Chrome 76.0.3809.100
## Reproduction link
[https://stackblitz.com/edit/angular-qm4dq1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qm4dq1?file=src/app/app.component.ts)
## Steps to reproduce
1.点击secure-text按钮
2.点击ok

3.点击login-password按钮
4.点击ok
## What is expected?
正常运行
## What is actually happening?
ERROR
Error: Cannot read property 'call' of undefined
## Other?
![modal](https://user-images.githubusercontent.com/34148806/63480050-06026d80-c4c3-11e9-8c17-deb227ed458b.gif)

**Comment by fisherspy** [comment]
#543
