### ISSUE TITLE
安卓系统下 ImagePicker图片选择器无法实现多图选择

### ISSUE THREAD

**Issue by sy759874469** [NG-ZORRO/ng-zorro-antd-mobile#545]
如题

**Comment by fisherspy** [comment]
@sy759874469 小米MIX系统浏览器验证多选OK。请告诉具体机型与系统版本，有可能是手机供应商修改了webview导致。

**Comment by HelloValue** [comment]
我有遇到同样的问题。安卓系统下，微信浏览器内无法支持文件的多选，并且不支持其他文件的选择（.pdf，xlsx等）。iOS下无此类问题。
我的应用版本为：angular 10+antd-mobile 3.0，手机为小米的mix 3，系统为MIUI 12.0。
