### ISSUE TITLE
TextareaItem 控件，如果在类 Pupop 窗口下使用，并设置 [autoHeight]="true"，当 Pupop 窗口弹出后，TextareaItem 组件内<textarea>的高度被设置为零，即：height: 0px

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd-mobile#546]
## Version
1.0.0-beta.0
## Environment
angular 7
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-9mmn3i?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-9mmn3i?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
点击 Open Popup 按钮，在显示的form中，Text1 与  Text2 被设置为  [autoHeight]="true"，其控件中的 <textarea>的高度被设置为零，无法使用。

Text3 和 Text4 没有设置 autoHeight，可正常使用。

## What is expected?
Text1 和 Text2 可以正常工作
## What is actually happening?
Text1 和 Text2 中的 <textarea> 的高度为零，无法使用
## Other?
0.12.5 版本没有此问题

**Comment by fisherspy** [comment]
#571
