### ISSUE TITLE
支持服务器端渲染吗? 如果有支持目前到什么程度了?

### ISSUE THREAD

**Issue by xujunzhou** [NG-ZORRO/ng-zorro-antd-mobile#547]
## What problem does this feature solve?
支持服务器端渲染吗? 如果有支持目前到什么程度了?
## What does the proposed API look like?
支持服务器端渲染吗? 如果有支持目前到什么程度了?

**Comment by 3fuyu** [comment]
服务端渲染需要以项目为单位进行，需要结合你的项目进行改造

**Comment by 3fuyu** [comment]
https://angular.cn/guide/universal

**Comment by xujunzhou** [comment]
@3fuyu 非常感谢您在百忙之中的回答.
