### ISSUE TITLE
建议未来更新能兼容以前的特性

### ISSUE THREAD

**Issue by DeMeng33** [NG-ZORRO/ng-zorro-antd-mobile#549]
## What problem does this feature solve?
为了修复bug，不得已升级1.0-beta，贵方所有人的努力代码上都看得到，但是遗留问题太多了，Model、Toast、ActionSheet、在我的工程中涉及110处更改，有的能通过全局替换来做，这还是比较容易的。现在在改InputItem的新特性，你们添加了content后彻底抛弃了对原来的支持，这使我平白增加了很多工作量，一共涉及99处、19个文件，还不能通过全局替换来实现。
## What does the proposed API look like?
例如InputItem:应该是
<InputItem [type]="'password'" [placeholder]="'****'" [content]="'密码'"></InputItem>
和
<InputItem [type]="'password'" [placeholder]="'****'">密码</InputItem>
都能实现功能。而现在，第二种方式组件是不能接收到content的

**Comment by fisherspy** [comment]
不好意思给你带来了困扰，inputItem目前的问题是如果使用以前的调用方式会有隐藏的问题，一旦涉及多层ng-content嵌套就会出现问题，因此我们考虑很久决定不再支持旧有的调用方式。我们目前变更API主要是是为了1.0之后的稳定性，给你带来不便再次感到抱歉。
