### ISSUE TITLE
【Carousel走马灯】如何能阻止滑动冒泡

### ISSUE THREAD

**Issue by fanybook** [NG-ZORRO/ng-zorro-antd-mobile#55]
我把 【Carousel走马灯】 嵌套在 【Tabs标签页】里使用

他们都有滑动的效果，我的期望是滑动【Carousel走马灯】时，【Tabs标签页】不要跟着切换

现在的现象是：
1.小幅滑动时，可以只有【Carousel走马灯】切换，【Tabs标签页】未切换
2.但稍微幅度大点的滑动，这俩一起都切换了

**Comment by fisherspy** [comment]
@fanybook 请在https://stackblitz.com/edit/ng-zorro-antd-mobile-start 中重现出你想要问的问题后点 fork并在此issue中发布

**Comment by fanybook** [comment]
@fisherspy 我重现出不来，我把 tabs 粘进 https://stackblitz.com/edit/ng-zorro-antd-mobile-start 这里，根本不显示

我想做的就是  幻灯片滑动切换时，tabs不要切换
现在是滑动幅度稍大，tabs就会被切换

**Comment by fisherspy** [comment]
@fanybook 可以在官网Tabs的示例代码区块点击 Edit on StackBliz，修改后fork出来

**Comment by fanybook** [comment]
@fisherspy @Guoyuanqiang 
https://stackblitz.com/edit/angular-j3us68
浏览器里  滑动不好测

**Comment by fisherspy** [comment]
@fanybook 后续你可以将右边demo在在标签页打开，然后用模拟器模式即可。

**Comment by fanybook** [comment]
@fisherspy 哦  我是后端  第一次玩 ng

链接靠手机上就行了   你明白我想实现的需求了吗

**Comment by fanybook** [comment]
@fisherspy @Guoyuanqiang 
我提交了再现，怎么没有消息了 :(

**Comment by fisherspy** [comment]
@fanybook  #61

**Comment by fanybook** [comment]
@fisherspy 期待

**Comment by fisherspy** [comment]
> @fisherspy 期待，怎么看是否打包进新npm包

你看相关commit之后有新的release就说明新的npm包发布了

**Comment by fisherspy** [comment]
@fanybook 已修复，验证好了之后请关闭当前issue，谢谢！

**Comment by fanybook** [comment]
@fisherspy 我看npm更新了

但是我这样更新无法更到0.9.6，只能到0.9.5

npm update ng-zorro-antd-mobile
npm update ng-zorro-antd-mobile@0.9.6

**Comment by fisherspy** [comment]
> @fisherspy 我看npm更新了
> 
> 但是我这样更新无法更到0.9.6，只能到0.9.5
> 
> npm update ng-zorro-antd-mobile
> npm update ng-zorro-antd-mobile@0.9.6

你可以在package.json里修改版本号，然后npm install

**Comment by fanybook** [comment]
nice  完美
