### ISSUE TITLE
输入键盘挡住输入框

### ISSUE THREAD

**Issue by keyiis** [NG-ZORRO/ng-zorro-antd-mobile#550]
ios12.4 ipad mini
inputitem如果在页面底部，那么会被弹起的键盘遮住，官方的demo里也有这个问题

**Comment by fisherspy** [comment]
@keyiis 手机有这个问题吗?

**Comment by sWhite01111** [comment]
可以录个视频或者截图看看么

**Comment by Iurmy** [comment]
是的，我这看ios原生输入法应该是不挡的其他都挡。后来改成弹窗输入了。
另外挡住输入框的是，在浏览器中呼出输入法并获得焦点后，输入法上会有一行带有钥匙图标的东西

**Comment by sWhite01111** [comment]
我先close了，后面如果有提供详细的复现在线demo和视频，会再打开来看

**Comment by fisherspy** [comment]
@keyiis @Iurmy 请遇到问题的提供一下stackblitz 代码和demo

**Comment by Iurmy** [comment]
> @keyiis @Iurmy 请遇到问题的提供一下stackblitz 代码和demo

官网上有个扫码体验功能，数据录入下inputitem最下方有个手机号码，点一下。
（我在用这个项目，希望这个项目越做越好，也希望你们能去扫码体验多操作一下。）
