### ISSUE TITLE
Ionic4 中使用1.0bate版在release时报错

### ISSUE THREAD

**Issue by bhqt** [NG-ZORRO/ng-zorro-antd-mobile#551]
ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,106): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(19,106): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.

**Comment by bhqt** [comment]
angular 8，在debug模式下不报错

**Comment by bhqt** [comment]
应该是被ng-zorro的配置给冲突了

**Comment by bhqt** [comment]
重新试了下，确实是不行，急等，谢谢

**Comment by bhqt** [comment]
刚浏览了关闭的问题，确实是因为angular8的问题，顾关闭该问题

**Comment by fisherspy** [comment]
@bhqt  1.0.0-beta.1已支持Angular 8

**Comment by KeonaHu** [comment]
Angular : "@angular/cli": "~8.1.2",
NgZorroAntdMobile : "ng-zorro-antd-mobile": "^1.0.0-beta.1"
执行ng build --prod也是这个错误!
@fisherspy

**Comment by fisherspy** [comment]
@KeonaHu 1.0.0-beta.2修复了这个错误
