### ISSUE TITLE
Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.

### ISSUE THREAD

**Issue by candy4290** [NG-ZORRO/ng-zorro-antd-mobile#552]
![image](https://user-images.githubusercontent.com/19907991/64141565-22939380-ce3b-11e9-9145-4c05a25d0750.png)
ng-zorro-antd-mobile版本：1.0.0-beta.0

Modal和ActionSheet中

在开发环境，没有任何问题。
打包后或者aot方式启动，触发弹窗或者actionsheet，报错：
![image](https://user-images.githubusercontent.com/19907991/64141649-7e5e1c80-ce3b-11e9-8845-ba575c327d54.png)

**Comment by fisherspy** [comment]
@candy4290 还没有支持8.0，你降级为7.0版本试试。

**Comment by fisherspy** [comment]
1.0.0-beta.1已支持Angular 8 @candy4290
