### ISSUE TITLE
跑马灯中图片在上滑会不显示

### ISSUE THREAD

**Issue by zt95599** [NG-ZORRO/ng-zorro-antd-mobile#556]
IOS上使用跑马灯功能 在微信公众号中跑马灯图片在上滑会不显示，在安卓手机正常

**Comment by fisherspy** [comment]
麻烦提供一个stackblitz demo，官方demo在微信里上划并不会不显示。

**Comment by zt95599** [comment]
https://stackblitz.com/edit/angular-kqmdoj

**Comment by fisherspy** [comment]
将pc chrome浏览器的模拟器设置为iphone5这样更小尺寸的更容易复现。

**Comment by fisherspy** [comment]
#615 这个可能会解决你的问题

**Comment by fisherspy** [comment]
@zt95599 新的一版出来后看看
