### ISSUE TITLE
ng-zorro-antd-mobile build报错

### ISSUE THREAD

**Issue by ccjhpu** [NG-ZORRO/ng-zorro-antd-mobile#563]
使用 npm run build -- --prod --aot， 报错，
"ng-zorro-antd-mobile": "^1.0.0-beta.1",
 "@angular/cli": "8.3.2",

报错如下
`
ERROR in node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(6,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signa tures. node_modules/ng-zorro-antd-mobile/ng-zorro-antd-mobile.d.ts.ListComponent.html(18,48): : Cannot invoke an expression whose type lacks a call signature. Type 'string | Function | TemplateRef<any>' has no compatible call signatures.
`

**Comment by fisherspy** [comment]
@ccjhpu 请问是如何复现的？

**Comment by ccjhpu** [comment]
您好，我ng-zorro-antd-mobile的版本是1.0.0-beta.1，angular/cli 版本是 8.3.2，
本地 dev 模式完全正常，就是在 build模式报错，使用的命令是  npm run build:aot

**Comment by ccjhpu** [comment]
@fisherspy 您好，我ng-zorro-antd-mobile的版本是1.0.0-beta.1，angular/cli 版本是 8.3.2，
本地 dev 模式完全正常，就是在 build模式报错，使用的命令是 npm run build:aot

**Comment by fisherspy** [comment]
@ccjhpu 你是build ng-zorro-antd-mobile组件库还是在你的项目里使用npm run build --aot， 能够在stackblitz提供代码demo

**Comment by ccjhpu** [comment]
@fisherspy 是在项目里面使用npm run build --aot报错，但是使用npm run build可以编译通过，
项目里面同时集成了ng-zorro-antd(8.2.1)和ng-zorro-antd-mobile(1.0.0-beta.1)，很抱歉啊项目是公司项目暂时不方便。

**Comment by bcddh** [comment]
@fisherspy 
新建项目
@angular/core@8.2.4  
@angular/cli@8.3.3 
ng-zorro-antd-mobile@1.0.0-beta.1
编译命令 ng build --prod就会报这个错误。

**Comment by fisherspy** [comment]
@bcddh 有钉钉么？群里说一声，发个文件夹给我？

**Comment by fisherspy** [comment]
该问题是因为 ng add ng-zorro-antd-mobile 引发，如果直接 npm install ng-zorro-antd-mobile --save不会出现该问题，因此需要排查schematics

**Comment by fisherspy** [comment]
@ccjhpu @bcddh 1.0.0-beta.2已修复

**Comment by ccjhpu** [comment]
@fisherspy 真心感谢，我这边也可以啦，辛苦啦
