### ISSUE TITLE
滑动操作组件不生效

### ISSUE THREAD

**Issue by bairuochen** [NG-ZORRO/ng-zorro-antd-mobile#567]
用ionic 新建一个项目, 然后add ng-zorro-antd-mobile ,直接使用SwipeAction component ,发现滑动只触发事件,但是并没有滑出操作框
![image](https://user-images.githubusercontent.com/29061646/64330799-32aa9f00-d004-11e9-8a9a-12a99641c0c4.png)

**Comment by crayon1127** [comment]
好像是和ionic-content冲突  content里面只包含滑动组件就不会生效  我另一个页面还有分段器其他内容就可以使用

**Comment by bairuochen** [comment]
这样啊,我试试,那就是与ionic兼容上还是有问题是吧,好的,谢谢,麻烦了!


------------------ 原始邮件 ------------------
发件人: "crayon1127"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 上午9:24
收件人: "NG-ZORRO/ng-zorro-antd-mobile"<ng-zorro-antd-mobile@noreply.github.com>;
抄送: "陈恺"<1224473421@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NG-ZORRO/ng-zorro-antd-mobile] 滑动操作组件不生效 (#567)




好像是和ionic-content冲突  content里面只包含滑动组件就不会生效  我另一个页面还有分段器其他内容就可以使用

**Comment by bairuochen** [comment]
试了一下,好像确实只与ion-content有冲突,header和footer都没有问题

**Comment by fisherspy** [comment]
#569
