### ISSUE TITLE
在Tabs组件内部嵌套Picker组件时，第二个以及大于第二个TabPane里面的Picker组件不显示

### ISSUE THREAD

**Issue by ccjhpu** [NG-ZORRO/ng-zorro-antd-mobile#568]
检查元素得知 picker容器的样式设置为
`
.am-picker-popup, .am-picker-popup-mask, .am-picker-popup-wrap {
    position: fixed;
    bottom: 0;
    left: 0;
}
`
觉得是  ` position: fixed;`的原因，因为这个样式导致picker弹出时是在第一个TabPane里面

**Comment by fisherspy** [comment]
与 #498 原因相同，请先使用动态创建picker的方式。

**Comment by ccjhpu** [comment]
@fisherspy 你好，我参考了您给的链接，还是没有解决，我把主要代码贴出来了，麻烦帮忙看下
https://stackblitz.com/edit/angular-diowut

第一次使用这个工具，现在展示的效果跟我本地有出入。您只看tabs和picker部分就行

**Comment by ccjhpu** [comment]
代码在 app.component.html 第24行

**Comment by fisherspy** [comment]
先参考 #601

**Comment by fisherspy** [comment]
#621 已修复 @ccjhpu

**Comment by fisherspy** [comment]
@ccjhpu 1.0.2版本已上线。
