### ISSUE TITLE
表单控件（inputItem,textareaitem等）为啥不实现setDisabledState()方法

### ISSUE THREAD

**Issue by to0simple** [NG-ZORRO/ng-zorro-antd-mobile#574]
## What problem does this feature solve?
表单控件（inputItem,textareaitem等）为啥不实现setDisabledState()方法，使用响应式表单体验好差，我想把表单控件disabled 还必须得在组件上添加，new formControl({value:'12',disabled:true})这样就不可以
## What does the proposed API look like?
setDisabledState(disabled: boolean){
    this._disabled = disabled;
    this.cdr.markForCheck();
  }
类似这种实现，响应式表单就可以new formControl({value:'123',disabled:true})

**Comment by love-YY** [comment]
我看源码 有一些没实现这个setDisabledState()，有的呢实现了这个方法却没有将变量绑定到元素

**Comment by to0simple** [comment]
#693

**Comment by to0simple** [comment]
#694

**Comment by to0simple** [comment]
#696
