### ISSUE TITLE
Steps步骤条 显示不正常问题

### ISSUE THREAD

**Issue by zt95599** [NG-ZORRO/ng-zorro-antd-mobile#584]
![image](https://user-images.githubusercontent.com/34113439/64940274-26410480-d896-11e9-8563-19d447d2cc65.png)
从后台循环加载数据到步骤条 显示不正常 点击浏览器刷新显示正常 
![image](https://user-images.githubusercontent.com/34113439/64940369-5e484780-d896-11e9-96a0-73cd4fdba292.png)

**Comment by fisherspy** [comment]
@zt95599 stackblitz demo
