### ISSUE TITLE
ActionSheet无法弹出

### ISSUE THREAD

**Issue by gas0324** [NG-ZORRO/ng-zorro-antd-mobile#587]
1.0.0-rc.0版本中 ActionSheet无法弹出，回退至1.0.0-beta.2则正常，不知该版本是做了什么改动文档没有修改吗

**Comment by fisherspy** [comment]
官网和stackblitz 样例都可以弹出啊，怎么不能弹出了？

**Comment by gas0324** [comment]
感谢回复！

在我去使用1.0.0-rc.0版本的时候，调用弹出ActionSheet的方法时，会报错：
ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.

使用方法：
showActionSheet() {
    const BUTTONS = ['Operation1', 'Operation2', 'Operation2', 'Delete', 'Cancel'];
    this._actionSheet.showActionSheetWithOptions(
      {
        options: BUTTONS,
        cancelButtonIndex: BUTTONS.length - 1,
        destructiveButtonIndex: BUTTONS.length - 2,
        title: 'title',
        maskClosable: true
      },
      buttonIndex => {
        console.log(buttonIndex);
      }
    );
  }

不太使用github，不会上传截图，请谅解

当我去降级到1.0.0-beta.2 这个版本时，可以正常弹出

**Comment by gas0324** [comment]
补充图片：
<img src="https://s2.ax1x.com/2019/09/17/n549UI.png">
<img src="https://s2.ax1x.com/2019/09/17/n54VKg.png">

**Comment by fisherspy** [comment]
@gas0324 angular cdk版本要升级。

**Comment by gas0324** [comment]
@fisherspy 好的
