### ISSUE TITLE
ListItem 中 extra 绑定点击方法并传递参数

### ISSUE THREAD

**Issue by gas0324** [NG-ZORRO/ng-zorro-antd-mobile#590]
我在使用ListItem的时候，用extra写了一个图标，由于是遍历出来的，所以希望传递一个参数到方法里，不知道有没有什么方法可以实现

<img src="https://s2.ax1x.com/2019/09/20/nj2S8H.png" alt="nj2S8H.png" border="0" />

**Comment by gas0324** [comment]
是否可以提供一个类似InputItem中的 onExtraClick 方法？

**Comment by 3fuyu** [comment]
> 是否可以提供一个类似InputItem中的 onExtraClick 方法？

ng-template放到对应dom内部即可拿到li的值
