### ISSUE TITLE
CheckboxItem组件disabled后原有选中状态丢失

### ISSUE THREAD

**Issue by zhh007** [NG-ZORRO/ng-zorro-antd-mobile#597]
## Version
1.0.1
## Environment
win10，qq浏览器10.5.1极速模式，ng-zorro-antd-mobile版本为1.0.1
## Reproduction link
[https://stackblitz.com/edit/angular-hqdper](https://stackblitz.com/edit/angular-hqdper)
## Steps to reproduce
如题
## What is expected?
显示禁用的选中状态
## What is actually happening?
无

**Comment by fisherspy** [comment]
#598
