### ISSUE TITLE
上拉刷新 是不是应该改成上拉加载更多？？？？？

### ISSUE THREAD

**Issue by Snowflake13** [NG-ZORRO/ng-zorro-antd-mobile#599]
## Version
1.0.1
## Environment
H5
## Reproduction link
[https://cuqy5c.run.stackblitz.io](https://cuqy5c.run.stackblitz.io)
## Steps to reproduce
没有步骤，原生
## What is expected?
上拉刷新 是不是应该改成上拉加载更多？？？？？
## What is actually happening?
上拉刷新 是不是应该改成上拉加载更多？？？？？
## Other?
上拉刷新 是不是应该改成上拉加载更多？？？？？

**Comment by fisherspy** [comment]
Ant Design Mobile规范是这样的，我们与React版本能保持一致。
