### ISSUE TITLE
Grid组件carousel按照文档无法正常现实

### ISSUE THREAD

**Issue by ferried** [NG-ZORRO/ng-zorro-antd-mobile#6]
1.如果不加最大行列是渲染不出来grid的
2.即使渲染出来也会报icon/text属性找不到的错误

**Comment by Guoyuanqiang** [comment]
@ferried 可以写个reprolink吗？https://stackblitz.com/edit/ng-zorro-antd-mobile-setup?file=src%2Fapp%2Fapp.component.html

**Comment by ferried** [comment]
stackblitz运行正常
看上去是我自己的问题

**Comment by ferried** [comment]
https://stackblitz.com/edit/ng-zorro-antd-mobile-start-oeuhj6
