### ISSUE TITLE
关于InputItem不显示text的问题

### ISSUE THREAD

**Issue by lament0** [NG-ZORRO/ng-zorro-antd-mobile#604]
## Version
1.0.1
## Environment
angular8 antd for mobile 0.9.x
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
 <InputItem [editable]="false" [value]="'not editable'">Name</InputItem> 
这个Name不显示，网页F12看，无此Div标签
## What is expected?
期望尽快解决，而且代码复制，之前有测试页面，这几天隐藏了？

## What is actually happening?
stackblitz的结果是正确的，本人重新构建了项目，inputitem还是没有text值，望回复一下原因
## Other?
QQ：1009780137 微信：17312783494

**Comment by sWhite01111** [comment]
#527 这次改动引入了一个breakchange，标签内容需要写入到content里面，如
 <InputItem  [editable]="false" [value]="'not editable'" [content]="'Name'"></InputItem>

**Comment by lament0** [comment]
还有关于Toast的问题，如下图；



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhenyun.Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 中午11:05
收件人:&nbsp;"NG-ZORRO/ng-zorro-antd-mobile"<ng-zorro-antd-mobile@noreply.github.com&gt;;
抄送:&nbsp;"沈海成"<1009780137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NG-ZORRO/ng-zorro-antd-mobile] 关于InputItem不显示text的问题 (#604)




#527 这次改动引入了一个breakchange，标签内容需要写入到content里面，如
 <InputItem  [editable]="false" [value]="'not editable'" [content]="'Name'"&gt;

**Comment by sWhite01111** [comment]
图是不是漏掉了

**Comment by lament0** [comment]
请查看附件，关于Toast，modal问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhenyun.Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 中午11:11
收件人:&nbsp;"NG-ZORRO/ng-zorro-antd-mobile"<ng-zorro-antd-mobile@noreply.github.com&gt;;
抄送:&nbsp;"沈海成"<1009780137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NG-ZORRO/ng-zorro-antd-mobile] 关于InputItem不显示text的问题 (#604)




图是不是漏掉了

**Comment by lament0** [comment]
![QQ浏览器截图20191030111608](https://user-images.githubusercontent.com/25712599/67826355-2f64f880-fb07-11e9-8f84-50941948c3d5.png)

**Comment by sWhite01111** [comment]
你重新修改下标题，或者提新的issue，这两个组件是其他同学负责的，需要转给对应的同学

**Comment by lament0** [comment]
好的，本次改动什么同步到最新版本呢，我这边引入content会报错

**Comment by sWhite01111** [comment]
直接使用最新版应该就可以的，这个改动是很早之前的了。建议最好把inputitem和model、toast的问题分开，我刚才的意思是说如果inputitem的问题解决了，你可以直接吧问题修改下

**Comment by lament0** [comment]
建议也修改下对应的官方文档，我刚瞅了瞅，如果改动是很久之前的，那么这个文档也应该更改一下~

**Comment by sWhite01111** [comment]
是的，官网还是0.9.X的版本，不好意思最近忙双十一忽略了
