### ISSUE TITLE
列表List-可输入列表List <inputitem>文档没及时更新

### ISSUE THREAD

**Issue by lament0** [NG-ZORRO/ng-zorro-antd-mobile#605]
## Version
1.0.1
## Environment
angular8 antd 1.0.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
inputitem标签写法过时，现在演示界面不显示text文字， stackblitz是正常的
## What is expected?
更新文档
## What is actually happening?
不显示text文字， stackblitz是正常的

**Comment by lament0** [comment]
![Uploading image.png…]()

**Comment by lament0** [comment]
![QQ浏览器截图20191031114720](https://user-images.githubusercontent.com/25712599/67917534-3c9be900-fbd4-11e9-9941-dc5b2d39493f.png)

**Comment by sWhite01111** [comment]
#606 pr已提
