### ISSUE TITLE
Carousel 只有一张图片时，resize导致显示错误

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd-mobile#613]
## Version
1.0.1
## Environment
win10 Google Chrome
## Reproduction link
[https://stackblitz.com/edit/angular-ypnhy9?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ypnhy9?file=src/app/app.component.ts)
## Steps to reproduce
1.只设置一张图片
2.改变窗体大小
![carousel](https://user-images.githubusercontent.com/34148806/69299729-3eddea00-0c4c-11ea-912d-51db42333b28.gif)

## What is expected?
正常显示
## What is actually happening?
图片消失
## Other?
官网 Edit On StackBlitz 与 Copy Generate Command 图标没显示

**Comment by fisherspy** [comment]
#615
