### ISSUE TITLE
InputItem type类型设置为money情况下，没有验证数字格式

### ISSUE THREAD

**Issue by oceanxue** [NG-ZORRO/ng-zorro-antd-mobile#618]
## Version
1.0.1
## Environment
chrome
## Reproduction link
[https://angular-eurlel-gchgwb.stackblitz.io](https://angular-eurlel-gchgwb.stackblitz.io)
## Steps to reproduce
InputItem type类型设置为money情况下，没有验证数字格式
## What is expected?
验证数字格式，以外不允许输入
## What is actually happening?
任意字符串，如：.021.364.1

**Comment by fisherspy** [comment]
#794
