### ISSUE TITLE
Drawer抽屉遮挡不住Badge徽标

### ISSUE THREAD

**Issue by oceanxue** [NG-ZORRO/ng-zorro-antd-mobile#623]
## Version
1.0.2
## Environment
chrome, 安卓
## Reproduction link
[https://angular-7g3drv.stackblitz.io](https://angular-7g3drv.stackblitz.io)
## Steps to reproduce
z-index大小
## What is expected?
Drawer抽屉遮挡Badge徽标
## What is actually happening?
Drawer抽屉遮挡不住Badge徽标

**Comment by Mr-Eve** [comment]
我能理解你是什么意思, 建议下次提供代码的复现链接, 当前你所提供的链接仅用于展示.
