### ISSUE TITLE
Tabs结合Drawer使用，初始化打开画面时抽屉会一闪收回

### ISSUE THREAD

**Issue by oceanxue** [NG-ZORRO/ng-zorro-antd-mobile#630]
## Version
1.0.2
## Environment
chrome
## Reproduction link
[https://angular-5f3cmn.stackblitz.io](https://angular-5f3cmn.stackblitz.io)
## Steps to reproduce
Tabs结合Drawer使用
## What is expected?
初始化打开画面时正常显示
## What is actually happening?
初始化打开画面时抽屉会一闪收回

**Comment by Mr-Eve** [comment]
请提供附带代码的demo

**Comment by fisherspy** [comment]
> 请提供附带代码的demo

https://stackblitz.com/edit/angular-5f3cmn?file=src/app/app.component.ts

**Comment by imecashust** [comment]
请问这个问题解决了嘛

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/724
