### ISSUE TITLE
DatePicker minDate禁用最小日期失效。

### ISSUE THREAD

**Issue by oceanxue** [NG-ZORRO/ng-zorro-antd-mobile#635]
## Version
1.0.2
## Environment
IOS，IE
## Reproduction link
[https://angular-tpzvoh.stackblitz.io](https://angular-tpzvoh.stackblitz.io)
## Steps to reproduce
设置minDate，比如先选择2020-01-14后，再改变选择2019年，月、日不重置到最小日期。还可以选择所有日期，禁用最小日期失效。
## What is expected?
重置到最小日期，禁用最小日期有效
## What is actually happening?
禁用最小日期失效

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/673
