### ISSUE TITLE
关于PullToRefresh组件上拉加载

### ISSUE THREAD

**Issue by Iurmy** [NG-ZORRO/ng-zorro-antd-mobile#636]
## What problem does this feature solve?
1.上拉加载数据时，完全不希望出现“刷新中。。。”以及“松开立即刷新”这个步骤，距离底部达到一定距离，需要立即执行回调函数，不知道大家有没有这个需求，而且这个步骤非常不流畅。
2.“刷新中。。。”这三个句号我以为发布1.0正式版就会去掉，不知道这三个句号有什么深意，本人希望去掉。
3.希望提供获取当前滚动距离的api。
（以上三个需求，我自己直接在node_modules修改实现了，更新会被覆盖。想fork一份修改之后发布npm自己用，不知道会不会侵权之类的）
## What does the proposed API look like?
需求3:
refreshState: {
       currentState: 'deactivate',
       drag: false，
       onScroll: (e) => {
              console.log(e.scrollTop);
       }
},

**Comment by nuonuoge** [comment]
可以通过自定义内容去掉文案
![image](https://user-images.githubusercontent.com/16378798/72490177-71255580-3851-11ea-82aa-a1846956d005.png)

```
<PullToRefresh [headerIndicator]="headerIndicator"></PullToRefresh>
headerIndicator: any = {
    activate: '',
    deactivate: '',
    release: '',
    finish: ''
  };
```

**Comment by Iurmy** [comment]
> 可以通过自定义内容去掉文案
> ![image](https://user-images.githubusercontent.com/16378798/72490177-71255580-3851-11ea-82aa-a1846956d005.png)
> 
> ```
> <PullToRefresh [headerIndicator]="headerIndicator"></PullToRefresh>
> headerIndicator: any = {
>     activate: '',
>     deactivate: '',
>     release: '',
>     finish: ''
>   };
> ```
嗯嗯这个我确实刚知道，谢谢了，当时改1和3的时候就直接把句号去掉了就没注意。不过默认其实也不应该有这三个句号
