### ISSUE TITLE
小程序能用吗

### ISSUE THREAD

**Issue by s-sy** [NG-ZORRO/ng-zorro-antd-mobile#638]

**Comment by coolyujiyu** [comment]
你可以用小程序嵌套webview，不过不建议这么搞

**Comment by s-sy** [comment]
换uniapp写了，不用这个了，
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "coolyujiyu"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 晚上10:33
收件人: "NG-ZORRO/ng-zorro-antd-mobile"<ng-zorro-antd-mobile@noreply.github.com&gt;; 
抄送: "要听音乐 "<860770924@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NG-ZORRO/ng-zorro-antd-mobile] 小程序能用吗 (#638)





 
你可以用小程序嵌套webview，不过不建议这么搞
