### ISSUE TITLE
在生命周期ngOnInit里面调Toast轻提示会报错ERROR Error: ApplicationRef.tick is called recursively

### ISSUE THREAD

**Issue by Steven2619** [NG-ZORRO/ng-zorro-antd-mobile#640]
## Version
1.0.2
## Environment
angular8.2.14
## Reproduction link
[https://stackblitz.com/edit/angular-c1dria?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-c1dria?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
在生命周期ngOnInit中调用ToastService的方法会报错
## What is expected?
解决报错，能正常关闭这个轻提示
## What is actually happening?
不能根本的解决报错
## Other?
虽然可以用setTimeOut的方式异步处理解决报错，但这不是最优解

**Comment by qiqiangwu** [comment]
组件还是有bug，最近怎么都没有人回复

**Comment by yimity** [comment]
有同样的错误。

**Comment by zhengmenghuang** [comment]
遇到一样的问题 目前通过加 定时器解决问题
setTimeout(() => this.toastService.loading('加载中...', 0), 0);

另外 modal的visible 不要用  只能用 ngModel  控制是否显示

**Comment by Nick-QI** [comment]
同样遇到，暂时只能用settimeout 来跳过 Docheck 阶段了；
希望有大佬能解决这个问题

**Comment by Nick-QI** [comment]
刚看了两个issues 都是同样的问题，都是以settimeout 解决然后关闭这个问题了。
估计这个也。。。

**Comment by DeMeng33** [comment]
遇到同样问题 无解。。。

**Comment by shuizhongxiong** [comment]
#795
