### ISSUE TITLE
Picker用户改变选中值后再次打开弹窗,默认选中的是旧值

### ISSUE THREAD

**Issue by WangHone** [NG-ZORRO/ng-zorro-antd-mobile#644]
## Version
1.0.2
## Environment
版本 80.0.3987.116（正式版本）; NG-ZORRO-MOBILE@1.0.2; WINDOWS10
## Reproduction link
[https://yqs6u4.run.stackblitz.io/](https://yqs6u4.run.stackblitz.io/)
## Steps to reproduce
组件设置默认选中崇文区，用户点击选择朝阳区以后，再次点击picker弹窗后默认选中的还是崇文区。
## What is expected?
再次点击picker弹窗后默认选中上次选择的朝阳区
## What is actually happening?
再次点击picker弹窗后默认选中了最开始的崇文区

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/677
