### ISSUE TITLE
请问什么时候能提供Angular9（ng9）的支持，谢谢！

### ISSUE THREAD

**Issue by cengit** [NG-ZORRO/ng-zorro-antd-mobile#645]
## What problem does this feature solve?
最新版本的angular加入了不少新功能，新项目想用新版ng，想问一下 antd 官方什么时候可以支持Angular9（ng9）？
你们做的非常棒，比较了几个UI库，还是觉得antd比较适合我们使用习惯，强烈希望早点支持ng9，各位老大，辛苦了
## What does the proposed API look like?
antd 官方什么时候可以支持Angular9

**Comment by fisherspy** [comment]
收到，正在计划中

**Comment by fssgh** [comment]
我试了下直接 改 node_modules/ng-zorro-antd-mobile/package.json中的这几个依赖就没有警告了，在NG9上跑好像也没什么问题
![QQ截图20200318171717](https://user-images.githubusercontent.com/14868289/76945080-02da3d80-693d-11ea-9852-26aee352d7a3.png)

**Comment by cengit** [comment]
看到有人回复说：试了下直接改 node_modules/ng-zorro-antd-mobile/package.json中的这几个依赖就没有警告了，在NG9上跑好像也没什么问题
![nnnngggggg](https://user-images.githubusercontent.com/3691806/77871680-66d2ff00-7277-11ea-8b7e-c63ebeb1c372.png)

**Comment by tirelyl** [comment]
#652
