### ISSUE TITLE
datePicker doesn't click ok also changes value

### ISSUE THREAD

**Issue by Liiiiimo** [NG-ZORRO/ng-zorro-antd-mobile#653]
## What problem does this feature solve?
datePicker doesn't click ok or cancel also changes value,  so i don't understand the meaning of button 'ok' and 'cancel'.
## What does the proposed API look like?
hope click ok change the value, cancel  do not change the value.

**Comment by nuonuoge** [comment]
you can use [ngModel]="value"， not [(ngModel)]="value"

**Comment by Mr-Eve** [comment]
@Liiiiimo any problems now?
