### ISSUE TITLE
when has mindate ,changing only the month, value will change to NaN

### ISSUE THREAD

**Issue by Liiiiimo** [NG-ZORRO/ng-zorro-antd-mobile#655]
## Version
1.0.3
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/angular-wohzue?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/angular-wohzue?embed=1&file=src/app/app.component.ts)
## Steps to reproduce
when has minDate, only change the month, you will find the problem
## What is expected?
will not be NaN
## What is actually happening?
value change to NaN
## Other?
also find in version1.0.5

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/673
