### ISSUE TITLE
ActionSheet 在子组件中使用，就会掉在屏幕的最下端，并且没有高度

### ISSUE THREAD

**Issue by ZiliXu-SH** [NG-ZORRO/ng-zorro-antd-mobile#660]
![image](https://user-images.githubusercontent.com/54844494/78981883-7eea2e80-7b53-11ea-91c1-f80ec218b837.png)

布局是flex布局，只有中间的按钮是绝对定位布局。

当我把ActionSheet移到外层父组件时，就不会有这个问题。

**Comment by Mr-Eve** [comment]
请使用https://stackblitz.com/复现
