### ISSUE TITLE
ng add ng-zorro-antd-mobile 支持多重项目的工作空间

### ISSUE THREAD

**Issue by chf007** [NG-ZORRO/ng-zorro-antd-mobile#665]
## What problem does this feature solve?
在使用了[多重项目](https://angular.cn/guide/file-structure#multiple-projects)的工作空间中执行 `ng add ng-zorro-antd-mobile` 命令，会报 `Path "/src/app/app.component.html" does not exist.` 错误。

我的 angular.json 配置如下，ng-zorro-antd-mobile 版本 2.0.1：
![image](https://user-images.githubusercontent.com/358650/79218985-f5ed3300-7e83-11ea-9080-2143d089b078.png)
## What does the proposed API look like?
执行 `ng add ng-zorro-antd-mobile` 命令，支持多重项目空间，如不输入 app 名，则使用 angular.json 的 defaultProject 配置的 app

**Comment by fisherspy** [comment]
不支持。
