### ISSUE TITLE
项目无法初始化：error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by HelloValue** [NG-ZORRO/ng-zorro-antd-mobile#671]
## Version
2.0.1
## Environment
Angular CLI: 8.3.26，Node: 10.16.3，Angular: 8.2.14，OS: win32 x64，typescript：3.5.3，webpack：4.39.2，@angular/cdk：9.2.1
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
1.ng new projetctname

2.ng add ng-zorro-antd-mobile
## What is expected?
successful run
## What is actually happening?
error TS1086: An accessor cannot be declared in an ambient context.
## Other?
提供的stackblitz.com demo 跟这个错误没有关系，因为是必填的，所以直接放了一个官网的地址上来。

**Comment by fisherspy** [comment]
@HelloValue cli要9.0以上，@angular版本我看也不是9.0以上，还有你的typescript版本太低了。如果你还是用angular 8 请使用1.x版本，如果需要使用2.0.1必须使用Angular 9.0及以上
