### ISSUE TITLE
在ionic5上安装不了

### ISSUE THREAD

**Issue by qq124719010** [NG-ZORRO/ng-zorro-antd-mobile#672]
## Version
2.0.1
## Environment
ionic 5
## Steps to reproduce
在ionic5项目里执行 ng add ng-zorro-antd-mobile 后报一堆错误。

**Comment by Agoni1** [comment]
把angular升级到9就ok了

**Comment by C-racker** [comment]
同，`TypeError: Attempted to assign to readonly property.`跑不起来

**Comment by qq124719010** [comment]
我自己琢磨出来了，把ionic5的依赖改成如下版本：
"dependencies": {
    "@angular/common": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "@capacitor/core": "2.0.1",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "core-js": "^2.5.4",
    "ng-zorro-antd-mobile": "^2.0.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@capacitor/cli": "2.0.1",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
并且使用 这个页面 http://ng.mobile.ant.design/#/docs/running-in-ionic/zh 提到的 **自行构建** 方法来构建，重点是 **不要在 app.modules.ts 中全局引入 ng-zorro-antd-mobile**，要在 使用组件的页面的module.ts里引入。

**Comment by nuonuoge** [comment]
如果是用ionic生成的项目 升级ng9 建议使用如下方式
```
npm install @ionic/angular@latest --save
ng update @angular/core @angular/cli --allow-dirty
```
