### ISSUE TITLE
ionic5 angular9 报错

### ISSUE THREAD

**Issue by C-racker** [NG-ZORRO/ng-zorro-antd-mobile#689]
## Version
2.0.1
## Environment
ionic:5.1 
angular:9.1.4 
ng-zorro-antd-mobile:2.0.1
typescript:3.8.3

## Reproduction link
[https://stackblitz.com/](https://stackblitz.com/)
## Steps to reproduce
直接运行会报错
![antd1](https://user-images.githubusercontent.com/20217449/81031537-1f1b4500-8ebf-11ea-9776-280887b4169b.png)
![antd2](https://user-images.githubusercontent.com/20217449/81031541-217d9f00-8ebf-11ea-969d-152f9670ac13.png)

## What is expected?
编译正常
## What is actually happening?

执行`npx ngcc`有以下警告
Warning: Entry point 'ng-zorro-antd-mobile' contains deep imports into '**/node_modules/@angular/compiler/src/render3/r3_ast'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by nuonuoge** [comment]
warning 官方解释 https://github.com/angular/angular/issues/35615
attempted to assign to readonly property未复现，如果是用ionic生成的项目 升级ng9 建议
```
npm install @ionic/angular@latest --save
ng update @angular/core @angular/cli --allow-dirty
```

**Comment by C-racker** [comment]
> warning 官方解释 [angular/angular#35615](https://github.com/angular/angular/issues/35615)
> attempted to assign to readonly property未复现，如果是用ionic生成的项目 升级ng9 建议使用如下方式
> 
> ```
> npm install @ionic/angular@latest --save
> ng update @angular/core @angular/cli --allow-dirty
> ```

试过了还是不行
web运行有更多报错信息
<img width="1292" alt="WX20200511-123539@2x" src="https://user-images.githubusercontent.com/20217449/81524504-05c53d80-9384-11ea-83fd-b6b7587d9746.png">

**Comment by fssgh** [comment]
是你自己的问题，我用ionic都没有问题的

**Comment by coolyujiyu** [comment]
这个倒是我也是ionic5+angular9也没问题
