### ISSUE TITLE
在angular 9 中会出现一个警告！望优化

### ISSUE THREAD

**Issue by fssgh** [NG-ZORRO/ng-zorro-antd-mobile#691]
警告内容如下：
[ng] Warning: Entry point 'ng-zorro-antd-mobile' contains deep imports into '/node_modules/@angular/compiler/src/render3/r3_ast'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/695
