### ISSUE TITLE
一个页面多个pulltorefresh，上拉冲突问题 

### ISSUE THREAD

**Issue by zzone** [NG-ZORRO/ng-zorro-antd-mobile#697]
## Version
2.0.1
## Environment
angular8  ng-zorro-antd-mobile 1.0.5
## Reproduction link
[https://stackblitz.com/edit/angular-pulltorefresh](https://stackblitz.com/edit/angular-pulltorefresh)
## Steps to reproduce
第一个tab页面，可以正常上拉刷新。切换到第二个tab页，没有上拉效果了。

经过定位发现PullToRefreshComponent组件重touchstart方法this._currentContentHeight = document.getElementsByTagName('pulltorefresh')[0].clientHeight;这句代码引起的错误。导致永远获取的是第一个pulltorefresh标签，后面的内容高度不一样了，导致没有上拉效果。
## What is expected?
正常上拉刷新
## What is actually happening?
会受第一个pulltorefresh的影响，偶尔可以，有时不可以上拉刷新。

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/698
