### ISSUE TITLE
'xxx' is not a known element

### ISSUE THREAD

**Issue by self-regulation** [NG-ZORRO/ng-zorro-antd-mobile#700]
try Examples get error,need help

<img width="456" alt="截屏2020-05-25 下午8 51 12" src="https://user-images.githubusercontent.com/16667591/82814410-b6c1f100-9ec9-11ea-8ecd-a5e6fccc5147.png">
<img width="899" alt="截屏2020-05-25 下午8 53 16" src="https://user-images.githubusercontent.com/16667591/82814499-dfe28180-9ec9-11ea-869a-d5a0658816de.png">
<img width="937" alt="截屏2020-05-25 下午8 53 48" src="https://user-images.githubusercontent.com/16667591/82814540-f2f55180-9ec9-11ea-84d0-cdf8b3b27b5c.png">

**Comment by sandyisone** [comment]
app.module.ts要imports：NgZorroAntdMobileModule

**Comment by xjchenhao** [comment]
我也遇到了这个问题。app.module.ts已经imports了NgZorroAntdMobileModule。

版本号是：1.0.5


```js
import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { NgZorroAntdMobileModule } from "ng-zorro-antd-mobile";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import { MyComponent } from "./component/my/my.component";



@NgModule({
  declarations: [AppComponent, MyComponent],
  imports: [BrowserModule, AppRoutingModule, NgZorroAntdMobileModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}

```

**Comment by zhoufeii** [comment]
请问一下这个问题最后解决了吗

**Comment by user-xm** [comment]
我刚刚遇到这个问题, 通过在特性模块中引入 `NgZorroAntdMobileModule` 解决.

**Comment by Mr-Eve** [comment]
这个问题还存在吗?
