### ISSUE TITLE
action-sheet在安卓UC浏览器无法拉起

### ISSUE THREAD

**Issue by fanguyun214** [NG-ZORRO/ng-zorro-antd-mobile#706]
## Version
2.0.1
## Environment
"@angular/cdk": "9.2.1",
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
点击拉起actionSheet
## What is expected?
期望在安卓UC正常拉起actionSheet
## What is actually happening?
在安卓UC不能拉起actionSheet

**Comment by tirelyl** [comment]
这个复现链接好像有点问题，并没有你描述的代码。能够确认一下吗，还有，可以确认一下是否是安装的最新版本

**Comment by xcLtw** [comment]
@fanguyun214  请在一周内确认这个问题在最新版是否存在并提供复现链接，一周内无回应会关闭issue
