### ISSUE TITLE
在Modal 组件中调用 pickerview 组件 动态设置 pickerview 初始值不生效

### ISSUE THREAD

**Issue by huashaoZhao** [NG-ZORRO/ng-zorro-antd-mobile#715]
<Modal [(ngModel)]="isBusinessHours" [popup]="true" [animationType]="'slide-up'" (onClose)="onCloseBusinessHours()">  
      <PickerView [data]="startSeasons" [cols]="1" [cascade]="true" [(ngModel)]="startTime"
                                    (ngModelChange)="onChangeStart($event)"></PickerView>
 </Modal>
startSeasons：动态从服务器获取数据
startTime：设置初始值  （不生效）

**Comment by nuonuoge** [comment]
You can use it like this to avoid error
```
<PickerView *ngIf="startSeasons && startSeasons.length >0" [data]="startSeasons" [cols]="1" [cascade]="true" [(ngModel)]="startTime"
(ngModelChange)="onChangeStart($event)">
```

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/718
