### ISSUE TITLE
ImagePicker图片选择器 旋转不生效

### ISSUE THREAD

**Issue by Mrlong93** [NG-ZORRO/ng-zorro-antd-mobile#716]
ImagePicker图片选择器 旋转不生效

image-picker.component.ts组件第95行 （transform: 'rotate(' + this.getRotation(item.orientation) + ')deg'） 设置错误

![image](https://user-images.githubusercontent.com/26369690/85351492-78eed180-b536-11ea-8de0-5434029d3666.png)

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/717

**Comment by Mr-Eve** [comment]
It looks like fixed already, therefore close this issue, you can open again if this problem appears again.
