### ISSUE TITLE
npm默认版本问题&自定义icon-url不生效

### ISSUE THREAD

**Issue by tworry** [NG-ZORRO/ng-zorro-antd-mobile#721]
## Version
2.0.3
## Environment
windows
## Reproduction link
[https://stackblitz.com/edit/无法在stackblitz重现，因为在stackblitz上2.0.3版本报错](https://stackblitz.com/edit/无法在stackblitz重现，因为在stackblitz上2.0.3版本报错)
### npm默认版本问题
```
ng new ng-zorro-antd-mobile-demo
cd ng-zorro-antd-mobile-demo
ng add ng-zorro-antd-mobile --theme
ng serve
```
然后就会报错。
仔细查看之后，发现 `ng-zorro-antd-mobile`版本为`1.0.6`。
然后进行如下操作
```
npm uninstall ng-zorro-antd-mobile-demo
ng add ng-zorro-antd-mobile@2.0.3 --theme
ng serve
```
正常进入页面

### 自定义icon-url不生效
- 在官网下载[font包](https://github.com/ant-design/ant-design/releases/download/resource/iconfont-3.x.zip)
- 解压后放在`assets/fonts`文件夹下
- 修改`theme.less`文件，如下:
```
@icon-url : "/assets/fonts/iconfont";
@brand-primary: #ffc600;
```
- 修改`app.component.html`如下:
```
<div Button [type]="'primary'">primary</div>
<Icon [type]="'check'"></Icon>
<Icon [type]="'bars'"></Icon>
```
- 第二个Icon没有生效,修改主题色生效了的。
## What is expected?
1.npm默认安装2.0.3版本
2.修改@icon-url会生效
## What is actually happening?
1.npm默认安装的是1.0.6版本
2.修改@icon-url不生效

**Comment by nuonuoge** [comment]
不使用@icon-url : "/assets/fonts/iconfont";方式，直接在angular.json中引入"src/assets/font/iconfont.js",`<Icon [type]="'icon-forward'"></Icon>`

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/728

**Comment by fisherspy** [comment]
@tworry
