### ISSUE TITLE
i18n 计划支持其他语言吗？比如说德语 什么的

### ISSUE THREAD

**Issue by cugzhaolei** [NG-ZORRO/ng-zorro-antd-mobile#730]
目前发现ng-zorro-mobile中支持5种语言
`export { default as en_US } from './en_US';
export { default as ru_RU } from './ru_RU';
export { default as sv_SE } from './sv_SE';
export { default as zh_CN } from './zh_CN';
export { default as da_DK } from './da_DK';
`
对于其他语言支持会做吗？或者我添加一个德语的支持，谢谢

**Comment by fisherspy** [comment]
欢迎PR👏
