### ISSUE TITLE
是否有方法可以知道当前有没有打开的modal对话框?

### ISSUE THREAD

**Issue by goldenfireking** [NG-ZORRO/ng-zorro-antd-mobile#737]
## What problem does this feature solve?
我想在路由跳转的时候检查是否有打开的对话框，文档里写了modalService有个openModals可以获取所有打开的对话框集合，但是实际使用时，modalService没有openModals这个属性，请问是为什么？
## What does the proposed API look like?
能够提供方法获取所有打开的modal

**Comment by xcLtw** [comment]
angular层问题，移步https://github.com/angular/angular
