### ISSUE TITLE
canlendar选择日期区间，button样式错乱。

### ISSUE THREAD

**Issue by Liiiiimo** [NG-ZORRO/ng-zorro-antd-mobile#746]
## Version
2.0.7
## Environment
angular: 9.13, ng-zorro-antd-mobile:2.0.7, window10
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
1、选择日期，已选开始时间，未选结束时间，button为active，实际不可点击;
2、已选开始时间和结束时间，button为disable，实际可点击。
## What is expected?
选择日期区间时，button样式正确。
## What is actually happening?
选择日期区间时，button样式不正确。
## Other?
![image](https://user-images.githubusercontent.com/32323168/93840043-8fd1cb00-fcc1-11ea-8ea9-404191ceff2b.png)

![image](https://user-images.githubusercontent.com/32323168/93840029-83e60900-fcc1-11ea-963c-18c280a223e8.png)

**Comment by nuonuoge** [comment]
@Liiiiimo Can you provide a stackblitz recurring address
