### ISSUE TITLE
how to use these styles in a separate component?

### ISSUE THREAD

**Issue by BrainBolder** [NG-ZORRO/ng-zorro-antd-mobile#747]
how to use these styles in a separate component:
// -------- import official less file -----------
@import '../node_modules/ng-zorro-antd-mobile/src/ng-zorro-antd-mobile.less';

styles do not work if you add them only to the component,
why they need to be installed angular.json?

**Comment by Mr-Eve** [comment]
Why you want to use styles in a separate component?
We recommand you config it in angular.json
