### ISSUE TITLE
button组件点击事件问题

### ISSUE THREAD

**Issue by Shandawei** [NG-ZORRO/ng-zorro-antd-mobile#75]
## Version
0.9.5
## Environment
常用的浏览器均是如此
## Reproduction link
[https://stackblitz.com/edit/angular-jshdse](https://stackblitz.com/edit/angular-jshdse)
## Steps to reproduce
在移动设备打开,按下按钮滚动页面,依然会触发事件.看了下组件,touch等事件的考虑太少,touchmove,touchcancel没有考虑在内,点击中滚动,长按等事件,均没有处理,导致的问题就是按钮不能碰,碰了必执行.建议不要自己写这些触控事件,太复杂,光touch,mouse太多,没有特殊的操作不建议使用此方式实现.
## What is expected?
正常的button点击操作,正常处理move等事件
## What is actually happening?
按钮不能碰,碰了必执行.
## Other?
建议不要自己写这些触控事件,太复杂,光touch,mouse太多,没有特殊的操作不建议使用此方式实现.

**Comment by BronzeCui** [comment]
#95 已修复
