### ISSUE TITLE
单选组件无法选择RadioItemGroup 

### ISSUE THREAD

**Issue by victory-wu** [NG-ZORRO/ng-zorro-antd-mobile#755]
## Version
1.0.6
## Environment
chrome 最新浏览器
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-zer3rw?file=package.json](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-zer3rw?file=package.json)
## Steps to reproduce
鼠标点击选项
## What is expected?
可以点击
## What is actually happening?
点击无效, 无法选中

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/756

**Comment by victory-wu** [comment]
thank u
