### ISSUE TITLE
TextareaItem bug

### ISSUE THREAD

**Issue by victory-wu** [NG-ZORRO/ng-zorro-antd-mobile#757]
## Version
3.0.3, 1.0.6 都有这个问题
## Environment
windows10  chrome 86 最新版本
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ckdkng?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ckdkng?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
点击按钮,  输入测试
## What is expected?
结果同步
## What is actually happening?
value  值与  结果不同步

**Comment by nuonuoge** [comment]
3.0.3版本测试没有问题
![image](https://user-images.githubusercontent.com/16378798/98315000-21975c80-2012-11eb-81e5-0348406324f5.png)

**Comment by victory-wu** [comment]
stackblitz   老是让我安装  core-js 又安装不上

**Comment by nuonuoge** [comment]
@victory-wu 你可以从demo地址打开 贴入你的代码测试
![image](https://user-images.githubusercontent.com/16378798/98322375-3845af80-2022-11eb-9cf5-fcf2c483d904.png)
