### ISSUE TITLE
How to create 'Picker' with code, like 'Toast, Modal' ?

### ISSUE THREAD

**Issue by gulullu** [NG-ZORRO/ng-zorro-antd-mobile#76]
I mean no this:

```javascript
      <ListItem Picker
                [extra]="name1"
                [arrow]="'horizontal'"
                [mask]=true
                [title]="'Areas'"
                [value]="value1"
                (onOk)="onOk1($event)"
      >
        Multiple & cascader
      </ListItem>
```

Just like Toast and Modal with this code:

```javascript
import { Injectable } from '@angular/core';
import { Toast, Modal } from 'ng-zorro-antd-mobile';
import { ToastType } from '../../enums/toast-type';
import { AlertType } from '../../enums/alert-type';

@Injectable({
  providedIn: 'root'
})
export class ToastAlertService {

  constructor(private _toast: Toast, private _modal: Modal) { }

  showToast(message: string, type?: ToastType, callback?: () => void) {
    const onClose = () => {
      if (callback) {
        callback();
      }
    };
    if (!type || type === ToastType.Text) {
      Toast.info(message, 2000, onClose);
    } else if (type === ToastType.NetwokError) {
      Toast.offline(message, 2000);
    } else if (type === ToastType.Success) {
      Toast.success(message, 2000, onClose);
    } else if (type === ToastType.Fail) {
      Toast.fail(message, 2000, onClose);
    } else if (type === ToastType.Loading) {
      Toast.loading(message, 0, onClose);
    }
  }

  showAlert(title: string, message: string, buttons: any[], alertType?: AlertType,
    placeholder?: string, callback?: (data?: string) => void) {

    if (!alertType || alertType === AlertType.Alert) {
      Modal.alert(title, message, buttons);
    } else {
      Modal.prompt(
        title,
        message,
        (data) => {
          if (callback) {
            callback(data);
          }
        },
        title,
        null,
        [placeholder]
      );
    }
  }
}
```

**Comment by Evin-An** [comment]
Hello, i find a problem that when you click the button for toasting, it will be invoked that the bootstrap method of Application. Have you ever encountered this problem?

**Comment by gulullu** [comment]
> Hello, i find a problem that when you click the button for a toast, it will be invoked that the bootstrap method of Application. Have you ever encountered this problem?

I don't know what you mean, but console  always log 'Angular is running in the development mode. Call enableProdMode() to enable the production mode' when a toast present.

**Comment by sWhite01111** [comment]
@gulullu Now  this is not supported，Picker does not provide such a service

**Comment by Guoyuanqiang** [comment]
> I mean no this:
> 
> ```js
>       <ListItem Picker
>                 [extra]="name1"
>                 [arrow]="'horizontal'"
>                 [mask]=true
>                 [title]="'Areas'"
>                 [value]="value1"
>                 (onOk)="onOk1($event)"
>       >
>         Multiple & cascader
>       </ListItem>
> ```
> 
> Just like Toast and Modal with this code:
> 
> ```js
> import { Injectable } from '@angular/core';
> import { Toast, Modal } from 'ng-zorro-antd-mobile';
> import { ToastType } from '../../enums/toast-type';
> import { AlertType } from '../../enums/alert-type';
> 
> @Injectable({
>   providedIn: 'root'
> })
> export class ToastAlertService {
> 
>   constructor(private _toast: Toast, private _modal: Modal) { }
> 
>   showToast(message: string, type?: ToastType, callback?: () => void) {
>     const onClose = () => {
>       if (callback) {
>         callback();
>       }
>     };
>     if (!type || type === ToastType.Text) {
>       Toast.info(message, 2000, onClose);
>     } else if (type === ToastType.NetwokError) {
>       Toast.offline(message, 2000);
>     } else if (type === ToastType.Success) {
>       Toast.success(message, 2000, onClose);
>     } else if (type === ToastType.Fail) {
>       Toast.fail(message, 2000, onClose);
>     } else if (type === ToastType.Loading) {
>       Toast.loading(message, 0, onClose);
>     }
>   }
> 
>   showAlert(title: string, message: string, buttons: any[], alertType?: AlertType,
>     placeholder?: string, callback?: (data?: string) => void) {
> 
>     if (!alertType || alertType === AlertType.Alert) {
>       Modal.alert(title, message, buttons);
>     } else {
>       Modal.prompt(
>         title,
>         message,
>         (data) => {
>           if (callback) {
>             callback(data);
>           }
>         },
>         title,
>         null,
>         [placeholder]
>       );
>     }
>   }
> }
> ```

i will support this way later.
