### ISSUE TITLE
Steps组件的current值动态改变之后没反应

### ISSUE THREAD

**Issue by qq124719010** [NG-ZORRO/ng-zorro-antd-mobile#760]
## Version
3.0.3
## Environment
ionic 5
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-esrxa1?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-esrxa1?file=src/app/app.component.html)
## Steps to reproduce
设置 Steps 的 current 值为一个变量，然后动态改变这个变量值 
## What is expected?
能动态响应current值的变化
## What is actually happening?
没变化

**Comment by timothyBrake** [comment]
Ran into this issues as well! See https://stackblitz.com/edit/angular-jinct4

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/762
