### ISSUE TITLE
step输入字母报错，而且可以显示。

### ISSUE THREAD

**Issue by qinhuachang** [NG-ZORRO/ng-zorro-antd-mobile#771]
## Version
3.0.3
## Environment
https://ng.mobile.ant.design/version/2012.0.7#/components/stepper/zh
## Reproduction link
[https://qumjsf--run.stackblitz.io](https://qumjsf--run.stackblitz.io)
## Steps to reproduce
1、输入字母显示：NaN;
2、即使限制了最大值，也可以输入大值。
## What is expected?
不予许输入字母，可以输入的值在范围内。
## What is actually happening?
NaN

**Comment by fisherspy** [comment]
#787
