### ISSUE TITLE
修改default的button的宽度有时右侧border会消失

### ISSUE THREAD

**Issue by Acessss** [NG-ZORRO/ng-zorro-antd-mobile#782]
## Version
4.0.0
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/angular-lfn26t?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-lfn26t?file=src/app/app.component.ts)
## Steps to reproduce
调整default按钮的百分比宽度即可复现
## What is expected?
border正常显示
## What is actually happening?
右侧border消失

**Comment by nuonuoge** [comment]
提供的这个地址调整百分比宽度，border没有消失
