### ISSUE TITLE
Component InputItem Type Money Keyboard not defaulted to English

### ISSUE THREAD

**Issue by ferrry1090** [NG-ZORRO/ng-zorro-antd-mobile#784]
## What problem does this feature solve?
Hi Devs, I would like to ask how can we change the language for the InputItem? Currently it is showing as a Chinese Characters, Thanks!
## What does the proposed API look like?
I would like to show it as defaulted English.

**Comment by nuonuoge** [comment]
Do you mean the online case?

**Comment by ferrry1090** [comment]
> Do you mean the online case?

Thanks sir replying this while you are so busy.
I am using the <InputItem [type]="'money'">
But when I check it in the browser, the button is in Chinese words. Could we have this defaulted as English?

Screenshot for your reference
![image](https://user-images.githubusercontent.com/50064299/117631831-d1f34280-b1a6-11eb-9030-e883547409d5.png)

**Comment by nuonuoge** [comment]
you can set en_us in your app，http://ng.mobile.ant.design/#/components/locale-provider/zh
```import { LOCAL_PROVIDER_TOKEN, en_US } from 'ng-zorro-antd-mobile';

@NgModule({
  ...
  imports     : [ NgZorroAntdMobileModule ],
  providers   : [ { provide: LOCAL_PROVIDER_TOKEN, useValue: en_US } ]
})
export class AppModule { }```

**Comment by ferrry1090** [comment]
> you can set en_us in your app，http://ng.mobile.ant.design/#/components/locale-provider/zh
> 
> ```
> import { LOCAL_PROVIDER_TOKEN, en_US } from 'ng-zorro-antd-mobile';
> @NgModule({
>   ...
>   imports     : [ NgZorroAntdMobileModule ],
>   providers   : [ { provide: LOCAL_PROVIDER_TOKEN, useValue: en_US } ]
> })
> export class AppModule { }```
> ```

Thanks a lot, I did check last time it is not there, thanks for updating it :)
tested and It works like charm.
Thanks for you hard work sir, keep it up!
