### ISSUE TITLE
InputItem 类型为money，设置国际化为en_US，弹出的小键盘“确定按钮”不会变成英文OK

### ISSUE THREAD

**Issue by yuxl01** [NG-ZORRO/ng-zorro-antd-mobile#785]
## Version
4.0.0
## Environment
官网api demo
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
选择英文其他的按钮都变为英文，但是小键盘的国际化未成功
## What is expected?
变为ok
## What is actually happening?
中文文字 确定

**Comment by nuonuoge** [comment]
![image](https://user-images.githubusercontent.com/16378798/117625477-a2ddd080-b1a8-11eb-9ab8-ef86dd99f423.png)
这边测试是ok的 显示的不是中文
