### ISSUE TITLE
Stepper步进器 手动输入除数字之外的字符，显示值会变为NaN 

### ISSUE THREAD

**Issue by yuxl01** [NG-ZORRO/ng-zorro-antd-mobile#787]
## Version
4.0.0
## Environment
本地和官网demo上均为此现象
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
手动输入其他字符，变为NaN
## What is expected?
变为默认值0
## What is actually happening?
NaN

**Comment by fisherspy** [comment]
#791
