### ISSUE TITLE
请问组件兼容ionic3吗

### ISSUE THREAD

**Issue by microwin168** [NG-ZORRO/ng-zorro-antd-mobile#8]
请问组建兼容ionic3吗

**Comment by Guoyuanqiang** [comment]
暂时还没有去兼容ionic3

**Comment by fisherspy** [comment]
等我们在Ionic3的兼容性测试完成后再看。

**Comment by fisherspy** [comment]
@microwin168 请问你的项目从Ionic 3迁移到Ionic 4的成本有多高？

**Comment by microwin168** [comment]
@fisherspy 项目还在测试选型中。感觉ionic4才beta版不稳定，所以考虑暂时用ionic3

**Comment by nuonuoge** [comment]
@microwin168  ionic4虽然还在beta版本，但是搭配zorro使用问题不大，我这个项目从3升级到4也就用了两天时间左右，3的路由太难用了，4的插件用的不多，这块不知道和3区别多大https://github.com/nuonuoge/ionic4_angular6_elm

**Comment by jerrytang67** [comment]
用了这个还要ionic4干嘛.@nuonuoge ionic3的路由的确很变态

**Comment by nuonuoge** [comment]
@jerrytang67  打包成手机app需要，当然你也可以用其他的

**Comment by izee** [comment]
手动搭建cordova环境也可以啊，没必要一定要和ionic一起使用

**Comment by gulullu** [comment]
兼容 ionic 4就好，现在 ionic 4还有很多问题。
