### ISSUE TITLE
tabbar可不可以只加载当前选中的tab页面中的服务接口

### ISSUE THREAD

**Issue by Jamesnakes** [NG-ZORRO/ng-zorro-antd-mobile#806]
## What problem does this feature solve?
如果tabbar有四个，进入项目会加载全部tabbar的接口，导致页面加载速度会非常慢！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
## What does the proposed API look like?
给tabbar添加一个参数

**Comment by xcLtw** [comment]
无效，这个问题不应该由框架解决

**Comment by ZENETOM** [comment]
https://ng.ant.design/components/tabs/zh#components-tabs-demo-lazy
nz-tabs的懒加载了解一下？没激活的tabs不会被加载
