### ISSUE TITLE
执行ng build打包后，上传到服务器，使用安卓浏览器访问页面，发现ModalService.alert的弹窗不展示遮罩

### ISSUE THREAD

**Issue by witonjieyang** [NG-ZORRO/ng-zorro-antd-mobile#809]
## Version
4.0.0
## Environment
安卓
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-x7nugy-qhuuwn?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-x7nugy-qhuuwn?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
1. ng new xxx新建一个Angular项目

2. ng add ng-zorro-antd-mobile 安装ng mobile

3. 在任意页面点击按钮，使用modalService.alert打开一个弹窗

4. 使用ng build --prod打包，并发布到服务器上

5. 使用安卓手机访问服务器上的页面，点击按钮打开弹窗，发现没有遮罩，ios上没有此问题
## What is expected?
打开的弹窗有遮罩
## What is actually happening?
没有遮罩

**Comment by shuizhongxiong** [comment]
只有发到服务器上，且用安卓手机浏览器扫码才会出现这个问题么？

我这边用安卓微信扫码没有复现，你的重现链接失效了，麻烦重新搞一个吧。

**Comment by xcLtw** [comment]
@witonjieyang  请在一周内确认这个问题在最新版是否存在并提供复现链接，一周内无回应会关闭issue
