### ISSUE TITLE
在angular 13下，使用ng-zorro-antd-mobile会报错

### ISSUE THREAD

**Issue by Luxcy** [NG-ZORRO/ng-zorro-antd-mobile#812]
![f25dd31d5e749694caf6951f1bb57a4](https://user-images.githubusercontent.com/13784184/143844824-14301b88-0e8e-4b31-bd3d-33c3606677d2.png)

**Comment by zhaoxiongxing** [comment]
官方 目前只适配到angular12

**Comment by xcLtw** [comment]
6.0.0版本支持 angular 13版本使用哦
