### ISSUE TITLE
官网历史文档无法查看

### ISSUE THREAD

**Issue by Coder7777** [NG-ZORRO/ng-zorro-antd-mobile#821]
## Version
2.0.7
## Environment
https://ng.mobile.ant.design/version/undefined
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-mobile-start?file=src/app/app.component.ts)
## Steps to reproduce
浏览https://ng.mobile.ant.design，通过官网右上角的下拉框无法查看旧版本的文档。
浏览器地址被导航到https://ng.mobile.ant.design/version/undefined。
## What is expected?
能正常访问历史版本的文档
## What is actually happening?
跳转到类似404的页面

**Comment by xcLtw** [comment]
@Coder7777     具体是哪个版本不可以查看呢?

**Comment by shuizhongxiong** [comment]
#822

**Comment by shuizhongxiong** [comment]
#822
