### ISSUE TITLE
使用Stepper组件时，如何设置数字键盘？

### ISSUE THREAD

**Issue by Coder7777** [NG-ZORRO/ng-zorro-antd-mobile#824]
## What problem does this feature solve?
使用Stepper组件时，如果用户点击Input直接进行输入，此时弹出的键盘是26个字母 数字的完整键盘。
其实这时候用户需要的只是纯数字键盘。
能否在Stepper组件上暴露一些属性，用于给开发人员设置弹出的键盘类型。
## What does the proposed API look like?
`  <Stepper keyboard=“numeric” >  </Stepper>`

`  <Stepper keyboard=“ text” >  </Stepper>`

**Comment by xcLtw** [comment]
步进器用于数值调整，之后会修改为直接唤起数字键盘，不添加输入类型支持

**Comment by xcLtw** [comment]
参见：https://github.com/NG-ZORRO/ng-zorro-antd-mobile/pull/832
