### ISSUE TITLE
支持微信和支付宝小程序开发吗？

### ISSUE THREAD

**Issue by cnbillow** [NG-ZORRO/ng-zorro-antd-mobile#847]
或者有没有计划支持？大概多久实现？

**Comment by mshmyw** [comment]
此仓库为基于ant design mobile设计规范的H5版Web Angular组件库。
如果你需要在微信或支付宝上投放H5应用，或者采用小程序套壳H5方案（即小程序<webview>加载H5应用），那么应该可以使用。
如果你这边是完全采用原生小程序view来构建页面的话，就不适合使用本方案。另外，如果你要投放微信或支付宝小程序，建议使用他们的官方组件库，例如支付宝小程序组件库：https://mini.ant.design/

**Comment by cnbillow** [comment]
谢谢回复
