### ISSUE TITLE
预计什么时候适配Angular 14？

### ISSUE THREAD

**Issue by ymind** [NG-ZORRO/ng-zorro-antd-mobile#848]
## What problem does this feature solve?
如题
## What does the proposed API look like?
适配Angular 14

**Comment by Coder7777** [comment]
感觉好像没人维护的样子

**Comment by ymind** [comment]
> 感觉好像没人维护的样子

没办法，谁让我是angular的10年老粉呢？可是angular的组件生态那是相当不好，新人也不愿意学，搞得最近都有心思换vue了……

**Comment by rxxy** [comment]
是不是转战ionic好一点哈哈

**Comment by Coder7777** [comment]
> 是不是转战ionic好一点哈哈

我是ionic和zorro混合用，部分组件ionic不提供。不得已采用zorro。

不过目前来看，好像zorro都不怎么维护了。

**Comment by Zebra-web** [comment]
> > 是不是转战ionic好一点哈哈
> 
> 我是ionic和zorro混合用，部分组件ionic不提供。不得已采用zorro。
> 
> 不过目前来看，好像zorro都不怎么维护了。

我们公司也是，ionic没有的就用zorro，难得有移动版的却没人维护了

**Comment by Zebra-web** [comment]
> > 感觉好像没人维护的样子
> 
> 没办法，谁让我是angular的10年老粉呢？可是angular的组件生态那是相当不好，新人也不愿意学，搞得最近都有心思换vue了……

我今年进的公司让我从vue转到了ng，上手还算容易，但往深了走也确实难，尤其ng学习资源也很少

**Comment by ymind** [comment]
> > > 感觉好像没人维护的样子
> > 
> > 
> > 没办法，谁让我是angular的10年老粉呢？可是angular的组件生态那是相当不好，新人也不愿意学，搞得最近都有心思换vue了……
> 
> 我今年进的公司让我从vue转到了ng，上手还算容易，但往深了走也确实难，尤其ng学习资源也很少

其实我认为ng的入门并不难。2013年首次接触angular v1的时候，我也只用了一天就熟悉了，一周内搭建了一个后台开发框架，后续工作效率也是飞起。后来接触v2的时候，当时ts还不太成熟，没实际使用过，直到v6我才升级，一直入坑zorro到现在的v14。

ng的各组件模块功能划分很清晰，做大型胖客户端很爽，管理维护也不容易乱。

vue我近些年没怎么用了，但看同事们写的代码，总感觉属于无组织无纪律，大多数同事不屑于组件封装，导致类似的东西你一个我一个，代码体系反而是越来越庞大。

不可否认，现在vue组件生态甩ng好几条街，但我仍然没做好转vue的准备，历史包袱太重是最大的原因。

**Comment by fssgh** [comment]
哎，没有人维护了。。。只能把组件代码搞下来放进项目里了自己修了。。。升到ng14没问题。。。。。现在vue3不也是用ts的了吗？组件主要是样式效果不会搞。。。可以抄一下vue3优化的组件到ng中来用。。。。

**Comment by ymind** [comment]
> 哎，没有人维护了。。。只能把组件代码搞下来放进项目里了自己修了。。。升到ng14没问题。。。。。现在vue3不也是用ts的了吗？组件主要是样式效果不会搞。。。可以抄一下vue3优化的组件到ng中来用。。。。

我打算试试 https://github.com/hellof2e/quark-design

**Comment by Zebra-web** [comment]
> > 哎，没有人维护了。。。只能把组件代码搞下来放进项目里了自己修了。。。升到ng14没问题。。。。。现在vue3不也是用ts的了吗？组件主要是样式效果不会搞。。。可以抄一下vue3优化的组件到ng中来用。。。。
> 
> 我打算试试 https://github.com/hellof2e/quark-design

对这个我今天也看见了，值得关注

**Comment by timothyBrake** [comment]
Hi how to upgrade to ng14 yourself? Thanks? Also posted the same question here https://stackoverflow.com/questions/74491514/ng-zorro-mobile-support-for-angular-14-angular-15
