### ISSUE TITLE
日历Calendar选择日期区间按钮样式问题

### ISSUE THREAD

**Issue by Atowp** [NG-ZORRO/ng-zorro-antd-mobile#852]
## Version
6.0.0
## Environment
stackblitz
## Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
1.选中开始时间，确认按钮为蓝色，状态却为禁用状态；
2.再选中结束时间，确认按钮为灰色，点击状态正常。
## What is expected?
1.选中开始时间，确认按钮为灰色，状态为禁用；
2.再选中结束时间，确认按钮为蓝色，点击状态正常。
## What is actually happening?
1.选中开始时间，确认按钮为蓝色，状态却为禁用状态；
2.再选中结束时间，确认按钮为灰色，点击状态正常。
## Other?
官网可重现

**Comment by yuizhixiaocaiji** [comment]
为啥这么久了还是没人修复呀。
