### ISSUE TITLE
IN18 error while using LocaleProvider

### ISSUE THREAD

**Issue by kkalpha** [NG-ZORRO/ng-zorro-antd-mobile#88]
## Version
0.9.6
## Environment
Angular 6, NG Zorro Mobile 0.9.6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-5slbsk](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-5slbsk)
## Steps to reproduce
1. add proverders: { provide: LOCAL_PROVIDER_TOKEN, useValue: en_US } in AppModule
2. add  import { LOCAL_PROVIDER_TOKEN, en_US } from 'ng-zorro-antd-mobile'; in AppModule
3. cause import compilation error says: ng-zorro-antd-mobile has not exported member LOCAL_PROVIDER_TOKEN
## What is expected?
import successfully
## What is actually happening?
cause import compilation error

**Comment by fisherspy** [comment]
please check out the local provider stackblitz demo.

**Comment by kkalpha** [comment]
> please check out the local provider stackblitz demo.

The reproduce steps is based on the stackblitz demo,just added the import statement and provider section, cause error as in step 3

**Comment by fisherspy** [comment]
why do you need to add the provider?

**Comment by kkalpha** [comment]
> why do you need to add the provider?
To  configuring antd locale text globally.
And I followed this document: http://ng.mobile.ant.design/#/components/locale-provider/en

**Comment by fisherspy** [comment]
@kkalpha 0.9.8版本导出了LOCAL_PROVIDER_TOKEN，请验证
