### ISSUE TITLE
有没有计划适配小程序的框架？

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd-mobile#9]
请问  有没有计划 出angular版的小程序框架 ， 小程序需求很大 需要大厂支持啊 。 美团有vue的mpvue虽然很坑不怎么维护了，  京东有react的taro 看样子还不错[微笑]

**Comment by fisherspy** [comment]
等NG-ZORRO-MOBILE成熟之后再考虑。

**Comment by DreamPWJ** [comment]
如果支持完美小程序  使用人数 和 star估计数量会飙升
